<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 14 Patent Infographics with R | The WIPO Manual on Open Source Patent Analytics (2nd edition)</title>
  <meta name="description" content="A practical introduction to free and open source tools for patent analytics." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 14 Patent Infographics with R | The WIPO Manual on Open Source Patent Analytics (2nd edition)" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A practical introduction to free and open source tools for patent analytics." />
  <meta name="github-repo" content="wipo-analytics/manual_bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 14 Patent Infographics with R | The WIPO Manual on Open Source Patent Analytics (2nd edition)" />
  
  <meta name="twitter:description" content="A practical introduction to free and open source tools for patent analytics." />
  



<meta name="date" content="2021-01-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="patent-analytics-with-plotly.html"/>
<link rel="next" href="scientific-literature-with-rplos.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">The WIPO Manual on Open Source Patent Analytics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Frontmatter</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#authorship"><i class="fa fa-check"></i><b>0.1</b> Authorship</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i><b>1</b> Preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="preface.html"><a href="preface.html#acknowledgements"><i class="fa fa-check"></i><b>1.1</b> Acknowledgements</a></li>
<li class="chapter" data-level="1.2" data-path="preface.html"><a href="preface.html#further-information"><i class="fa fa-check"></i><b>1.2</b> Further information</a></li>
<li class="chapter" data-level="1.3" data-path="preface.html"><a href="preface.html#conditions-of-use"><i class="fa fa-check"></i><b>1.3</b> Conditions of use</a></li>
<li class="chapter" data-level="1.4" data-path="preface.html"><a href="preface.html#disclaimer"><i class="fa fa-check"></i><b>1.4</b> Disclaimer</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>2</b> Introduction</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction.html"><a href="introduction.html#structure"><i class="fa fa-check"></i><b>2.1</b> Structure</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="introduction.html"><a href="introduction.html#an-overview-of-open-source-and-free-software-tools"><i class="fa fa-check"></i><b>2.1.1</b> An Overview of Open Source and Free Software Tools</a></li>
<li class="chapter" data-level="2.1.2" data-path="introduction.html"><a href="introduction.html#approaching-patent-data"><i class="fa fa-check"></i><b>2.1.2</b> Approaching Patent Data</a></li>
<li class="chapter" data-level="2.1.3" data-path="introduction.html"><a href="introduction.html#obtaining-patent-data"><i class="fa fa-check"></i><b>2.1.3</b> Obtaining Patent Data</a></li>
<li class="chapter" data-level="2.1.4" data-path="introduction.html"><a href="introduction.html#cleaning-and-tidying-patent-data"><i class="fa fa-check"></i><b>2.1.4</b> Cleaning and Tidying Patent Data</a></li>
<li class="chapter" data-level="2.1.5" data-path="introduction.html"><a href="introduction.html#analysing-and-visualizing-patent-data"><i class="fa fa-check"></i><b>2.1.5</b> Analysing and Visualizing Patent Data</a></li>
<li class="chapter" data-level="2.1.6" data-path="introduction.html"><a href="introduction.html#sharing-data-and-the-writing-of-the-manual"><i class="fa fa-check"></i><b>2.1.6</b> Sharing Data and The Writing of the Manual</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="the-patent-analytics-workflow.html"><a href="the-patent-analytics-workflow.html"><i class="fa fa-check"></i><b>3</b> The Patent Analytics Workflow</a>
<ul>
<li class="chapter" data-level="3.1" data-path="the-patent-analytics-workflow.html"><a href="the-patent-analytics-workflow.html#scoping-search"><i class="fa fa-check"></i><b>3.1</b> Scoping Search</a></li>
<li class="chapter" data-level="3.2" data-path="the-patent-analytics-workflow.html"><a href="the-patent-analytics-workflow.html#exploratory-data-visualisation"><i class="fa fa-check"></i><b>3.2</b> Exploratory data visualisation</a></li>
<li class="chapter" data-level="3.3" data-path="the-patent-analytics-workflow.html"><a href="the-patent-analytics-workflow.html#defined-search"><i class="fa fa-check"></i><b>3.3</b> Defined Search</a></li>
<li class="chapter" data-level="3.4" data-path="the-patent-analytics-workflow.html"><a href="the-patent-analytics-workflow.html#core-dataset"><i class="fa fa-check"></i><b>3.4</b> Core Dataset</a></li>
<li class="chapter" data-level="3.5" data-path="the-patent-analytics-workflow.html"><a href="the-patent-analytics-workflow.html#cleaning-the-core-dataset"><i class="fa fa-check"></i><b>3.5</b> Cleaning the Core Dataset</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="the-patent-analytics-workflow.html"><a href="the-patent-analytics-workflow.html#splitting-data"><i class="fa fa-check"></i><b>3.5.1</b> Splitting Data</a></li>
<li class="chapter" data-level="3.5.2" data-path="the-patent-analytics-workflow.html"><a href="the-patent-analytics-workflow.html#cleaning-data"><i class="fa fa-check"></i><b>3.5.2</b> Cleaning Data</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="the-patent-analytics-workflow.html"><a href="the-patent-analytics-workflow.html#visualise-report"><i class="fa fa-check"></i><b>3.6</b> Visualise &amp; Report</a></li>
<li class="chapter" data-level="3.7" data-path="the-patent-analytics-workflow.html"><a href="the-patent-analytics-workflow.html#conclusion"><i class="fa fa-check"></i><b>3.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html"><i class="fa fa-check"></i><b>4</b> An Overview of Tools</a>
<ul>
<li class="chapter" data-level="4.1" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#general-tools"><i class="fa fa-check"></i><b>4.1</b> General Tools</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#open-office"><i class="fa fa-check"></i><b>4.1.1</b> <span>Open Office</span></a></li>
<li class="chapter" data-level="4.1.2" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#google-sheets"><i class="fa fa-check"></i><b>4.1.2</b> <span>Google Sheets</span></a></li>
<li class="chapter" data-level="4.1.3" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#data-studio"><i class="fa fa-check"></i><b>4.1.3</b> Data Studio</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#cleaning-tools"><i class="fa fa-check"></i><b>4.2</b> Cleaning Tools</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#open-refine-formerly-google-refine"><i class="fa fa-check"></i><b>4.2.1</b> <span>Open Refine</span> (formerly Google Refine)</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#data-mining"><i class="fa fa-check"></i><b>4.3</b> Data Mining</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#rstudio"><i class="fa fa-check"></i><b>4.3.1</b> <span>RStudio</span></a></li>
<li class="chapter" data-level="4.3.2" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#rapidminer-studio"><i class="fa fa-check"></i><b>4.3.2</b> <span>RapidMiner Studio</span></a></li>
<li class="chapter" data-level="4.3.3" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#knime"><i class="fa fa-check"></i><b>4.3.3</b> <span>KNIME</span></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#data-visualization"><i class="fa fa-check"></i><b>4.4</b> Data visualization</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#google-charts"><i class="fa fa-check"></i><b>4.4.1</b> <span>Google Charts</span></a></li>
<li class="chapter" data-level="4.4.2" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#tableau-public"><i class="fa fa-check"></i><b>4.4.2</b> <span>Tableau Public</span></a></li>
<li class="chapter" data-level="4.4.3" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#r-and-rstudio"><i class="fa fa-check"></i><b>4.4.3</b> R and RStudio</a></li>
<li class="chapter" data-level="4.4.4" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#shiny"><i class="fa fa-check"></i><b>4.4.4</b> Shiny</a></li>
<li class="chapter" data-level="4.4.5" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#other-visualization-tools"><i class="fa fa-check"></i><b>4.4.5</b> Other visualization Tools</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#network-visualization"><i class="fa fa-check"></i><b>4.5</b> Network Visualization</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#gephi"><i class="fa fa-check"></i><b>4.5.1</b> <span>Gephi</span></a></li>
<li class="chapter" data-level="4.5.2" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#nodexl"><i class="fa fa-check"></i><b>4.5.2</b> <span>NodeXL</span></a></li>
<li class="chapter" data-level="4.5.3" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#pajek"><i class="fa fa-check"></i><b>4.5.3</b> <span>Pajek</span></a></li>
<li class="chapter" data-level="4.5.4" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#vos-viewer"><i class="fa fa-check"></i><b>4.5.4</b> <span>VOS Viewer</span></a></li>
<li class="chapter" data-level="4.5.5" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#hive-plots"><i class="fa fa-check"></i><b>4.5.5</b> <span>Hive Plots</span></a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#infographics"><i class="fa fa-check"></i><b>4.6</b> Infographics</a></li>
<li class="chapter" data-level="4.7" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#geographical-mapping"><i class="fa fa-check"></i><b>4.7</b> Geographical Mapping</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#openstreetmap"><i class="fa fa-check"></i><b>4.7.1</b> <span>OpenStreetMap</span></a></li>
<li class="chapter" data-level="4.7.2" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#leaflet"><i class="fa fa-check"></i><b>4.7.2</b> <span>Leaflet</span></a></li>
<li class="chapter" data-level="4.7.3" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#tableau-public-1"><i class="fa fa-check"></i><b>4.7.3</b> <span>Tableau Public</span></a></li>
<li class="chapter" data-level="4.7.4" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#qgis"><i class="fa fa-check"></i><b>4.7.4</b> <span>QGIS</span></a></li>
<li class="chapter" data-level="4.7.5" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#geonames.org."><i class="fa fa-check"></i><b>4.7.5</b> <span>Geonames.org</span>.</a></li>
<li class="chapter" data-level="4.7.6" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#cartodb"><i class="fa fa-check"></i><b>4.7.6</b> <span>CartoDB</span></a></li>
<li class="chapter" data-level="4.7.7" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#highcharts"><i class="fa fa-check"></i><b>4.7.7</b> <span>Highcharts</span></a></li>
<li class="chapter" data-level="4.7.8" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#datawrapper"><i class="fa fa-check"></i><b>4.7.8</b> <span>Datawrapper</span></a></li>
<li class="chapter" data-level="4.7.9" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#plotly"><i class="fa fa-check"></i><b>4.7.9</b> <span>Plotly</span></a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#text-mining"><i class="fa fa-check"></i><b>4.8</b> Text Mining</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#tidytext"><i class="fa fa-check"></i><b>4.8.1</b> <span>Tidytext</span></a></li>
<li class="chapter" data-level="4.8.2" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#weka"><i class="fa fa-check"></i><b>4.8.2</b> <span>Weka</span></a></li>
<li class="chapter" data-level="4.8.3" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#nltk"><i class="fa fa-check"></i><b>4.8.3</b> <span>NLTK</span></a></li>
<li class="chapter" data-level="4.8.4" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#spacy"><i class="fa fa-check"></i><b>4.8.4</b> Spacy</a></li>
<li class="chapter" data-level="4.8.5" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#annotation-tools-for-machine-learning"><i class="fa fa-check"></i><b>4.8.5</b> Annotation Tools for Machine Learning</a></li>
<li class="chapter" data-level="4.8.6" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#word-trees"><i class="fa fa-check"></i><b>4.8.6</b> Word Trees</a></li>
<li class="chapter" data-level="4.8.7" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#google-word-trees-on-the-google-developers-site-provides-instructions-for-generating-word-trees-using-javascript."><i class="fa fa-check"></i><b>4.8.7</b> <span>Google Word Trees</span> on the Google Developers site provides instructions for generating word trees using Javascript.</a></li>
<li class="chapter" data-level="4.8.8" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#r-and-the-tm-package"><i class="fa fa-check"></i><b>4.8.8</b> R and the <code>tm</code> package</a></li>
<li class="chapter" data-level="4.8.9" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#python-and-text-mining"><i class="fa fa-check"></i><b>4.8.9</b> Python and Text Mining</a></li>
<li class="chapter" data-level="4.8.10" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#other-text-mining-resources"><i class="fa fa-check"></i><b>4.8.10</b> Other text mining resources</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#round-up"><i class="fa fa-check"></i><b>4.9</b> Round Up</a></li>
<li class="chapter" data-level="4.10" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#the-checklist"><i class="fa fa-check"></i><b>4.10</b> The Checklist</a></li>
<li class="chapter" data-level="4.11" data-path="an-overview-of-tools.html"><a href="an-overview-of-tools.html#credits"><i class="fa fa-check"></i><b>4.11</b> Credits</a></li>
</ul></li>
<li class="part"><span><b>I Approaching Patent Data</b></span></li>
<li class="chapter" data-level="5" data-path="patent-datafields.html"><a href="patent-datafields.html"><i class="fa fa-check"></i><b>5</b> Patent Datafields</a>
<ul>
<li class="chapter" data-level="5.1" data-path="patent-datafields.html"><a href="patent-datafields.html#what-is-a-patent"><i class="fa fa-check"></i><b>5.1</b> What is a Patent?</a></li>
<li class="chapter" data-level="5.2" data-path="patent-datafields.html"><a href="patent-datafields.html#as-a-form-of-intellectual-property-right"><i class="fa fa-check"></i><b>5.2</b> As a form of intellectual property right</a></li>
<li class="chapter" data-level="5.3" data-path="patent-datafields.html"><a href="patent-datafields.html#patents-as-a-type-of-document"><i class="fa fa-check"></i><b>5.3</b> Patents as a type of document</a></li>
<li class="chapter" data-level="5.4" data-path="patent-datafields.html"><a href="patent-datafields.html#basic-data-types"><i class="fa fa-check"></i><b>5.4</b> Basic Data Types</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="patent-datafields.html"><a href="patent-datafields.html#synthetic-genomes"><i class="fa fa-check"></i><b>5.4.1</b> <span>Synthetic Genomes</span></a></li>
<li class="chapter" data-level="5.4.2" data-path="patent-datafields.html"><a href="patent-datafields.html#original-front-page"><i class="fa fa-check"></i><b>5.4.2</b> <span>Original Front Page</span></a></li>
<li class="chapter" data-level="5.4.3" data-path="patent-datafields.html"><a href="patent-datafields.html#espacenet-front-page"><i class="fa fa-check"></i><b>5.4.3</b> <span>espacenet Front Page</span></a></li>
<li class="chapter" data-level="5.4.4" data-path="patent-datafields.html"><a href="patent-datafields.html#description"><i class="fa fa-check"></i><b>5.4.4</b> <span>Description</span></a></li>
<li class="chapter" data-level="5.4.5" data-path="patent-datafields.html"><a href="patent-datafields.html#claims"><i class="fa fa-check"></i><b>5.4.5</b> <span>Claims</span></a></li>
<li class="chapter" data-level="5.4.6" data-path="patent-datafields.html"><a href="patent-datafields.html#family-members"><i class="fa fa-check"></i><b>5.4.6</b> <span>Family Members</span></a></li>
<li class="chapter" data-level="5.4.7" data-path="patent-datafields.html"><a href="patent-datafields.html#cited"><i class="fa fa-check"></i><b>5.4.7</b> <span>Cited</span></a></li>
<li class="chapter" data-level="5.4.8" data-path="patent-datafields.html"><a href="patent-datafields.html#citing"><i class="fa fa-check"></i><b>5.4.8</b> <span>Citing</span></a></li>
<li class="chapter" data-level="5.4.9" data-path="patent-datafields.html"><a href="patent-datafields.html#legal-status"><i class="fa fa-check"></i><b>5.4.9</b> <span>Legal Status</span></a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="patent-datafields.html"><a href="patent-datafields.html#round-up-1"><i class="fa fa-check"></i><b>5.5</b> Round Up</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>6</b> Datasets</a>
<ul>
<li class="chapter" data-level="6.1" data-path="datasets.html"><a href="datasets.html#the-datasets"><i class="fa fa-check"></i><b>6.1</b> The datasets</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="datasets.html"><a href="datasets.html#pizza-patent-datasets"><i class="fa fa-check"></i><b>6.1.1</b> Pizza patent datasets</a></li>
<li class="chapter" data-level="6.1.2" data-path="datasets.html"><a href="datasets.html#patent-landscape-reports-datasets"><i class="fa fa-check"></i><b>6.1.2</b> Patent Landscape Reports datasets</a></li>
<li class="chapter" data-level="6.1.3" data-path="datasets.html"><a href="datasets.html#packaged-datasets"><i class="fa fa-check"></i><b>6.1.3</b> Packaged Datasets</a></li>
<li class="chapter" data-level="6.1.4" data-path="datasets.html"><a href="datasets.html#other-datasets"><i class="fa fa-check"></i><b>6.1.4</b> Other datasets</a></li>
<li class="chapter" data-level="6.1.5" data-path="datasets.html"><a href="datasets.html#round-up-2"><i class="fa fa-check"></i><b>6.1.5</b> Round Up</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Obtaining Patent Data</b></span></li>
<li class="chapter" data-level="7" data-path="databases.html"><a href="databases.html"><i class="fa fa-check"></i><b>7</b> Databases</a>
<ul>
<li class="chapter" data-level="7.0.1" data-path="databases.html"><a href="databases.html#introduction-1"><i class="fa fa-check"></i><b>7.0.1</b> Introduction</a></li>
<li class="chapter" data-level="7.1" data-path="databases.html"><a href="databases.html#the-databases"><i class="fa fa-check"></i><b>7.1</b> The Databases</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="databases.html"><a href="databases.html#the-lens"><i class="fa fa-check"></i><b>7.1.1</b> <span>The Lens</span></a></li>
<li class="chapter" data-level="7.1.2" data-path="databases.html"><a href="databases.html#patentscope"><i class="fa fa-check"></i><b>7.1.2</b> <span>Patentscope</span></a></li>
<li class="chapter" data-level="7.1.3" data-path="databases.html"><a href="databases.html#espacenet"><i class="fa fa-check"></i><b>7.1.3</b> <span>espacenet</span></a></li>
<li class="chapter" data-level="7.1.4" data-path="databases.html"><a href="databases.html#latipat"><i class="fa fa-check"></i><b>7.1.4</b> <span>LATIPAT</span></a></li>
<li class="chapter" data-level="7.1.5" data-path="databases.html"><a href="databases.html#epo-open-patent-services"><i class="fa fa-check"></i><b>7.1.5</b> <span>EPO Open Patent Services</span></a></li>
<li class="chapter" data-level="7.1.6" data-path="databases.html"><a href="databases.html#uspto-patents-view"><i class="fa fa-check"></i><b>7.1.6</b> <span>USPTO Patents View</span></a></li>
<li class="chapter" data-level="7.1.7" data-path="databases.html"><a href="databases.html#google-patents"><i class="fa fa-check"></i><b>7.1.7</b> <span>Google Patents</span></a></li>
<li class="chapter" data-level="7.1.8" data-path="databases.html"><a href="databases.html#google-prior-art-finder"><i class="fa fa-check"></i><b>7.1.8</b> <span>Google Prior Art Finder</span></a></li>
<li class="chapter" data-level="7.1.9" data-path="databases.html"><a href="databases.html#google-uspto-bulk-download"><i class="fa fa-check"></i><b>7.1.9</b> <span>Google USPTO Bulk download</span></a></li>
<li class="chapter" data-level="7.1.10" data-path="databases.html"><a href="databases.html#free-patents-online"><i class="fa fa-check"></i><b>7.1.10</b> <span>Free Patents Online</span></a></li>
<li class="chapter" data-level="7.1.11" data-path="databases.html"><a href="databases.html#depatisnet"><i class="fa fa-check"></i><b>7.1.11</b> <span>DEPATISnet</span></a></li>
<li class="chapter" data-level="7.1.12" data-path="databases.html"><a href="databases.html#oecd-patent-databases"><i class="fa fa-check"></i><b>7.1.12</b> <span>OECD Patent Databases</span></a></li>
<li class="chapter" data-level="7.1.13" data-path="databases.html"><a href="databases.html#epo-world-patent-statistical-database"><i class="fa fa-check"></i><b>7.1.13</b> <span>EPO World Patent Statistical Database</span></a></li>
<li class="chapter" data-level="7.1.14" data-path="databases.html"><a href="databases.html#other-data-sources"><i class="fa fa-check"></i><b>7.1.14</b> Other data sources</a></li>
<li class="chapter" data-level="7.1.15" data-path="databases.html"><a href="databases.html#patent2net-in-python"><i class="fa fa-check"></i><b>7.1.15</b> <span>Patent2Net</span> in Python</a></li>
<li class="chapter" data-level="7.1.16" data-path="databases.html"><a href="databases.html#python-epo-ops-client-by-gsong"><i class="fa fa-check"></i><b>7.1.16</b> <span>Python EPO OPS Client</span> by Gsong</a></li>
<li class="chapter" data-level="7.1.17" data-path="databases.html"><a href="databases.html#fung-institute-patent-server-for-uspto-data-in-json"><i class="fa fa-check"></i><b>7.1.17</b> <span>Fung Institute Patent Server</span> for USPTO data in JSON</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="patentscope-1.html"><a href="patentscope-1.html"><i class="fa fa-check"></i><b>8</b> Patentscope</a>
<ul>
<li class="chapter" data-level="8.1" data-path="patentscope-1.html"><a href="patentscope-1.html#introduction-2"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="patentscope-1.html"><a href="patentscope-1.html#collections-to-search"><i class="fa fa-check"></i><b>8.2</b> Collections to Search</a></li>
<li class="chapter" data-level="8.3" data-path="patentscope-1.html"><a href="patentscope-1.html#simple-search"><i class="fa fa-check"></i><b>8.3</b> Simple Search</a></li>
<li class="chapter" data-level="8.4" data-path="patentscope-1.html"><a href="patentscope-1.html#results"><i class="fa fa-check"></i><b>8.4</b> Results</a></li>
<li class="chapter" data-level="8.5" data-path="patentscope-1.html"><a href="patentscope-1.html#downloading-results"><i class="fa fa-check"></i><b>8.5</b> Downloading Results</a></li>
<li class="chapter" data-level="8.6" data-path="patentscope-1.html"><a href="patentscope-1.html#cross-lingual-searching"><i class="fa fa-check"></i><b>8.6</b> Cross Lingual Searching</a></li>
<li class="chapter" data-level="8.7" data-path="patentscope-1.html"><a href="patentscope-1.html#sequence-data"><i class="fa fa-check"></i><b>8.7</b> Sequence Data</a></li>
<li class="chapter" data-level="8.8" data-path="patentscope-1.html"><a href="patentscope-1.html#round-up-3"><i class="fa fa-check"></i><b>8.8</b> Round Up</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="the-lens-1.html"><a href="the-lens-1.html"><i class="fa fa-check"></i><b>9</b> The Lens</a>
<ul>
<li class="chapter" data-level="9.1" data-path="the-lens-1.html"><a href="the-lens-1.html#introduction-3"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="the-lens-1.html"><a href="the-lens-1.html#getting-started"><i class="fa fa-check"></i><b>9.2</b> Getting Started</a></li>
<li class="chapter" data-level="9.3" data-path="the-lens-1.html"><a href="the-lens-1.html#additional-features"><i class="fa fa-check"></i><b>9.3</b> Additional features</a></li>
<li class="chapter" data-level="9.4" data-path="the-lens-1.html"><a href="the-lens-1.html#visualisation"><i class="fa fa-check"></i><b>9.4</b> Visualisation</a></li>
<li class="chapter" data-level="9.5" data-path="the-lens-1.html"><a href="the-lens-1.html#working-with-texts"><i class="fa fa-check"></i><b>9.5</b> Working with texts</a></li>
<li class="chapter" data-level="9.6" data-path="the-lens-1.html"><a href="the-lens-1.html#patseq"><i class="fa fa-check"></i><b>9.6</b> PatSeq</a></li>
<li class="chapter" data-level="9.7" data-path="the-lens-1.html"><a href="the-lens-1.html#round-up-4"><i class="fa fa-check"></i><b>9.7</b> Round Up</a></li>
</ul></li>
<li class="part"><span><b>III Cleaning Patent Data</b></span></li>
<li class="chapter" data-level="10" data-path="open-refine.html"><a href="open-refine.html"><i class="fa fa-check"></i><b>10</b> Open Refine</a>
<ul>
<li class="chapter" data-level="10.1" data-path="open-refine.html"><a href="open-refine.html#install-open-refine"><i class="fa fa-check"></i><b>10.1</b> Install Open Refine</a></li>
<li class="chapter" data-level="10.2" data-path="open-refine.html"><a href="open-refine.html#create-a-project"><i class="fa fa-check"></i><b>10.2</b> Create a Project</a></li>
<li class="chapter" data-level="10.3" data-path="open-refine.html"><a href="open-refine.html#open-refine-basics"><i class="fa fa-check"></i><b>10.3</b> Open Refine Basics</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="open-refine.html"><a href="open-refine.html#open-refine-runs-in-a-browser"><i class="fa fa-check"></i><b>10.3.1</b> Open Refine runs in a browser</a></li>
<li class="chapter" data-level="10.3.2" data-path="open-refine.html"><a href="open-refine.html#open-refine-works-on-columns."><i class="fa fa-check"></i><b>10.3.2</b> Open Refine works on columns.</a></li>
<li class="chapter" data-level="10.3.3" data-path="open-refine.html"><a href="open-refine.html#open-refine-works-with-facets."><i class="fa fa-check"></i><b>10.3.3</b> Open Refine works with Facets.</a></li>
<li class="chapter" data-level="10.3.4" data-path="open-refine.html"><a href="open-refine.html#custom-facets"><i class="fa fa-check"></i><b>10.3.4</b> Custom Facets</a></li>
<li class="chapter" data-level="10.3.5" data-path="open-refine.html"><a href="open-refine.html#reordering-columns"><i class="fa fa-check"></i><b>10.3.5</b> Reordering Columns</a></li>
<li class="chapter" data-level="10.3.6" data-path="open-refine.html"><a href="open-refine.html#undo-and-redo"><i class="fa fa-check"></i><b>10.3.6</b> Undo and Redo</a></li>
<li class="chapter" data-level="10.3.7" data-path="open-refine.html"><a href="open-refine.html#exporting"><i class="fa fa-check"></i><b>10.3.7</b> Exporting</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="open-refine.html"><a href="open-refine.html#basic-cleaning"><i class="fa fa-check"></i><b>10.4</b> Basic Cleaning</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="open-refine.html"><a href="open-refine.html#changing-case"><i class="fa fa-check"></i><b>10.4.1</b> Changing case</a></li>
<li class="chapter" data-level="10.4.2" data-path="open-refine.html"><a href="open-refine.html#regularise-case"><i class="fa fa-check"></i><b>10.4.2</b> Regularise case</a></li>
<li class="chapter" data-level="10.4.3" data-path="open-refine.html"><a href="open-refine.html#remove-leading-and-trailing-whitespace"><i class="fa fa-check"></i><b>10.4.3</b> Remove leading and trailing whitespace</a></li>
<li class="chapter" data-level="10.4.4" data-path="open-refine.html"><a href="open-refine.html#add-columns"><i class="fa fa-check"></i><b>10.4.4</b> Add Columns</a></li>
<li class="chapter" data-level="10.4.5" data-path="open-refine.html"><a href="open-refine.html#address-encoding-and-related-problems"><i class="fa fa-check"></i><b>10.4.5</b> Address Encoding and related problems</a></li>
<li class="chapter" data-level="10.4.6" data-path="open-refine.html"><a href="open-refine.html#reformatting-dates"><i class="fa fa-check"></i><b>10.4.6</b> Reformatting dates</a></li>
<li class="chapter" data-level="10.4.7" data-path="open-refine.html"><a href="open-refine.html#access-additional-information"><i class="fa fa-check"></i><b>10.4.7</b> Access additional information</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="open-refine.html"><a href="open-refine.html#fill-blank-cells"><i class="fa fa-check"></i><b>10.5</b> Fill blank cells</a></li>
<li class="chapter" data-level="10.6" data-path="open-refine.html"><a href="open-refine.html#renaming-columns"><i class="fa fa-check"></i><b>10.6</b> Renaming columns</a></li>
<li class="chapter" data-level="10.7" data-path="open-refine.html"><a href="open-refine.html#exporting-data"><i class="fa fa-check"></i><b>10.7</b> Exporting Data</a></li>
<li class="chapter" data-level="10.8" data-path="open-refine.html"><a href="open-refine.html#splitting-applicants"><i class="fa fa-check"></i><b>10.8</b> Splitting Applicants</a>
<ul>
<li class="chapter" data-level="10.8.1" data-path="open-refine.html"><a href="open-refine.html#situation-1---first-applicants"><i class="fa fa-check"></i><b>10.8.1</b> Situation 1 - First Applicants</a></li>
<li class="chapter" data-level="10.8.2" data-path="open-refine.html"><a href="open-refine.html#situation-2---all-applicants"><i class="fa fa-check"></i><b>10.8.2</b> Situation 2 - All Applicants</a></li>
<li class="chapter" data-level="10.8.3" data-path="open-refine.html"><a href="open-refine.html#phonetic-fingerprint-metaphone-3-clustering"><i class="fa fa-check"></i><b>10.8.3</b> Phonetic Fingerprint (Metaphone 3) clustering</a></li>
<li class="chapter" data-level="10.8.4" data-path="open-refine.html"><a href="open-refine.html#levenshtein-edit-distance"><i class="fa fa-check"></i><b>10.8.4</b> Levenshtein Edit Distance</a></li>
<li class="chapter" data-level="10.8.5" data-path="open-refine.html"><a href="open-refine.html#ppm"><i class="fa fa-check"></i><b>10.8.5</b> PPM</a></li>
<li class="chapter" data-level="10.8.6" data-path="open-refine.html"><a href="open-refine.html#preparing-for-export"><i class="fa fa-check"></i><b>10.8.6</b> Preparing for export</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="open-refine.html"><a href="open-refine.html#round-up-5"><i class="fa fa-check"></i><b>10.9</b> Round Up</a></li>
<li class="chapter" data-level="10.10" data-path="open-refine.html"><a href="open-refine.html#useful-resources"><i class="fa fa-check"></i><b>10.10</b> Useful Resources</a></li>
</ul></li>
<li class="part"><span><b>IV Visualizing Patent Data</b></span></li>
<li class="chapter" data-level="11" data-path="tableau-public-2.html"><a href="tableau-public-2.html"><i class="fa fa-check"></i><b>11</b> Tableau Public</a>
<ul>
<li class="chapter" data-level="11.1" data-path="tableau-public-2.html"><a href="tableau-public-2.html#introduction-4"><i class="fa fa-check"></i><b>11.1</b> Introduction</a></li>
<li class="chapter" data-level="11.2" data-path="tableau-public-2.html"><a href="tableau-public-2.html#installing-tableau"><i class="fa fa-check"></i><b>11.2</b> Installing Tableau</a></li>
<li class="chapter" data-level="11.3" data-path="tableau-public-2.html"><a href="tableau-public-2.html#getting-started-1"><i class="fa fa-check"></i><b>11.3</b> Getting Started</a></li>
<li class="chapter" data-level="11.4" data-path="tableau-public-2.html"><a href="tableau-public-2.html#publication-trends"><i class="fa fa-check"></i><b>11.4</b> Publication Trends</a></li>
<li class="chapter" data-level="11.5" data-path="tableau-public-2.html"><a href="tableau-public-2.html#adding-new-data-sources"><i class="fa fa-check"></i><b>11.5</b> Adding New Data Sources</a></li>
<li class="chapter" data-level="11.6" data-path="tableau-public-2.html"><a href="tableau-public-2.html#creating-an-overview-dashboard"><i class="fa fa-check"></i><b>11.6</b> Creating an Overview Dashboard</a></li>
<li class="chapter" data-level="11.7" data-path="tableau-public-2.html"><a href="tableau-public-2.html#saving-display-and-privacy-settings"><i class="fa fa-check"></i><b>11.7</b> Saving, Display and Privacy Settings</a></li>
<li class="chapter" data-level="11.8" data-path="tableau-public-2.html"><a href="tableau-public-2.html#privacy-and-security"><i class="fa fa-check"></i><b>11.8</b> Privacy and Security</a></li>
<li class="chapter" data-level="11.9" data-path="tableau-public-2.html"><a href="tableau-public-2.html#round-up-6"><i class="fa fa-check"></i><b>11.9</b> Round Up</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="gephi-1.html"><a href="gephi-1.html"><i class="fa fa-check"></i><b>12</b> Gephi</a>
<ul>
<li class="chapter" data-level="12.1" data-path="gephi-1.html"><a href="gephi-1.html#installing-gephi"><i class="fa fa-check"></i><b>12.1</b> Installing Gephi</a></li>
<li class="chapter" data-level="12.2" data-path="gephi-1.html"><a href="gephi-1.html#opening-gephi-and-installing-plugins"><i class="fa fa-check"></i><b>12.2</b> Opening Gephi and Installing Plugins</a></li>
<li class="chapter" data-level="12.3" data-path="gephi-1.html"><a href="gephi-1.html#importing-a-file-to-gephi-with-the-converter-plugin"><i class="fa fa-check"></i><b>12.3</b> Importing a file to Gephi with the converter plugin</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="gephi-1.html"><a href="gephi-1.html#step-1.-open-gephi-and-choose-file-import"><i class="fa fa-check"></i><b>12.3.1</b> Step 1. Open Gephi and Choose File &gt; Import</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="gephi-1.html"><a href="gephi-1.html#sizing-and-colouring-nodes"><i class="fa fa-check"></i><b>12.4</b> Sizing and Colouring Nodes</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="gephi-1.html"><a href="gephi-1.html#filtering-the-data"><i class="fa fa-check"></i><b>12.4.1</b> Filtering the data</a></li>
<li class="chapter" data-level="12.4.2" data-path="gephi-1.html"><a href="gephi-1.html#setting-node-size"><i class="fa fa-check"></i><b>12.4.2</b> Setting Node Size</a></li>
<li class="chapter" data-level="12.4.3" data-path="gephi-1.html"><a href="gephi-1.html#colouring-the-nodes"><i class="fa fa-check"></i><b>12.4.3</b> Colouring the Nodes</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="gephi-1.html"><a href="gephi-1.html#laying-out-the-graph"><i class="fa fa-check"></i><b>12.5</b> Laying out the Graph</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="gephi-1.html"><a href="gephi-1.html#save-your-work"><i class="fa fa-check"></i><b>12.5.1</b> Save your work</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="gephi-1.html"><a href="gephi-1.html#adding-labels"><i class="fa fa-check"></i><b>12.6</b> Adding Labels</a></li>
<li class="chapter" data-level="12.7" data-path="gephi-1.html"><a href="gephi-1.html#using-the-preview-options"><i class="fa fa-check"></i><b>12.7</b> Using the Preview Options</a></li>
<li class="chapter" data-level="12.8" data-path="gephi-1.html"><a href="gephi-1.html#exporting-from-preview"><i class="fa fa-check"></i><b>12.8</b> Exporting from Preview</a></li>
<li class="chapter" data-level="12.9" data-path="gephi-1.html"><a href="gephi-1.html#resources"><i class="fa fa-check"></i><b>12.9</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="patent-analytics-with-plotly.html"><a href="patent-analytics-with-plotly.html"><i class="fa fa-check"></i><b>13</b> Patent Analytics with Plotly</a>
<ul>
<li class="chapter" data-level="13.1" data-path="patent-analytics-with-plotly.html"><a href="patent-analytics-with-plotly.html#introduction-5"><i class="fa fa-check"></i><b>13.1</b> Introduction</a></li>
<li class="chapter" data-level="13.2" data-path="patent-analytics-with-plotly.html"><a href="patent-analytics-with-plotly.html#getting-started-with-plotly"><i class="fa fa-check"></i><b>13.2</b> Getting Started with Plotly</a></li>
<li class="chapter" data-level="13.3" data-path="patent-analytics-with-plotly.html"><a href="patent-analytics-with-plotly.html#importing-files"><i class="fa fa-check"></i><b>13.3</b> Importing Files</a></li>
<li class="chapter" data-level="13.4" data-path="patent-analytics-with-plotly.html"><a href="patent-analytics-with-plotly.html#creating-a-graphic-online"><i class="fa fa-check"></i><b>13.4</b> Creating a Graphic Online</a></li>
<li class="chapter" data-level="13.5" data-path="patent-analytics-with-plotly.html"><a href="patent-analytics-with-plotly.html#working-with-plotly-in-r"><i class="fa fa-check"></i><b>13.5</b> Working with Plotly in R</a></li>
<li class="chapter" data-level="13.6" data-path="patent-analytics-with-plotly.html"><a href="patent-analytics-with-plotly.html#round-up-7"><i class="fa fa-check"></i><b>13.6</b> Round Up</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html"><i class="fa fa-check"></i><b>14</b> Patent Infographics with R</a>
<ul>
<li class="chapter" data-level="14.1" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#getting-started-2"><i class="fa fa-check"></i><b>14.1</b> Getting Started</a></li>
<li class="chapter" data-level="14.2" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#load-a-.csv-file-using-readr"><i class="fa fa-check"></i><b>14.2</b> Load a .csv file using <code>readr</code></a></li>
<li class="chapter" data-level="14.3" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#viewing-data"><i class="fa fa-check"></i><b>14.3</b> Viewing Data</a></li>
<li class="chapter" data-level="14.4" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#identifying-types-of-object"><i class="fa fa-check"></i><b>14.4</b> Identifying Types of Object</a></li>
<li class="chapter" data-level="14.5" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#working-with-data"><i class="fa fa-check"></i><b>14.5</b> Working with Data</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#select"><i class="fa fa-check"></i><b>14.5.1</b> Select</a></li>
<li class="chapter" data-level="14.5.2" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#adding-data-with-mutate"><i class="fa fa-check"></i><b>14.5.2</b> Adding data with <code>mutate()</code></a></li>
<li class="chapter" data-level="14.5.3" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#counting-data-using-count"><i class="fa fa-check"></i><b>14.5.3</b> Counting data using <code>count()</code></a></li>
<li class="chapter" data-level="14.5.4" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#rename-a-field-with-rename"><i class="fa fa-check"></i><b>14.5.4</b> Rename a field with <code>rename()</code></a></li>
<li class="chapter" data-level="14.5.5" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#make-a-quickplot-with-qplot"><i class="fa fa-check"></i><b>14.5.5</b> Make a quickplot with <code>qplot()</code></a></li>
<li class="chapter" data-level="14.5.6" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#filter-data-using-filter"><i class="fa fa-check"></i><b>14.5.6</b> Filter data using <code>filter()</code></a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#simplify-code-with-pipes"><i class="fa fa-check"></i><b>14.6</b> Simplify code with pipes <code>%&gt;%</code></a></li>
<li class="chapter" data-level="14.7" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#harmonising-data"><i class="fa fa-check"></i><b>14.7</b> Harmonising data</a></li>
<li class="chapter" data-level="14.8" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#country-trends-using-spread-and-pivot_wider"><i class="fa fa-check"></i><b>14.8</b> Country Trends using <code>spread()</code> and <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="14.9" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#tidying-data---separating-and-gathering"><i class="fa fa-check"></i><b>14.9</b> Tidying data - Separating and Gathering</a>
<ul>
<li class="chapter" data-level="14.9.1" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#trimming-with-stringr"><i class="fa fa-check"></i><b>14.9.1</b> Trimming with <code>stringr</code></a></li>
</ul></li>
<li class="chapter" data-level="14.10" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#selecting-applicants-using-filter"><i class="fa fa-check"></i><b>14.10</b> Selecting applicants using <code>filter()</code></a></li>
<li class="chapter" data-level="14.11" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#generating-ipc-tables"><i class="fa fa-check"></i><b>14.11</b> Generating IPC Tables</a>
<ul>
<li class="chapter" data-level="14.11.1" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#phrases-tables"><i class="fa fa-check"></i><b>14.11.1</b> Phrases Tables</a></li>
</ul></li>
<li class="chapter" data-level="14.12" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#creating-an-infographic-in-infogr.am"><i class="fa fa-check"></i><b>14.12</b> Creating an infographic in infogr.am</a>
<ul>
<li class="chapter" data-level="14.12.1" data-path="patent-infographics-with-r.html"><a href="patent-infographics-with-r.html#round-up-8"><i class="fa fa-check"></i><b>14.12.1</b> Round Up</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V Using APIs</b></span></li>
<li class="chapter" data-level="15" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html"><i class="fa fa-check"></i><b>15</b> Scientific Literature with Rplos</a>
<ul>
<li class="chapter" data-level="15.1" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#introduction-6"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#install-r-and-rstudio"><i class="fa fa-check"></i><b>15.2</b> Install R and RStudio</a></li>
<li class="chapter" data-level="15.3" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#create-a-project-1"><i class="fa fa-check"></i><b>15.3</b> Create A Project</a></li>
<li class="chapter" data-level="15.4" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#install-packages"><i class="fa fa-check"></i><b>15.4</b> Install Packages</a></li>
<li class="chapter" data-level="15.5" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#key-functions-in-rplos"><i class="fa fa-check"></i><b>15.5</b> Key functions in rplos</a></li>
<li class="chapter" data-level="15.6" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#data-fields-in-rplos"><i class="fa fa-check"></i><b>15.6</b> Data Fields in rplos</a></li>
<li class="chapter" data-level="15.7" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#basic-searching-using-searchplos-navigating-and-exporting-data"><i class="fa fa-check"></i><b>15.7</b> Basic Searching using <code>searchplos()</code>, Navigating and Exporting Data</a>
<ul>
<li class="chapter" data-level="15.7.1" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#creating-a-new-object-and-writing-to-file"><i class="fa fa-check"></i><b>15.7.1</b> Creating a New Object and Writing to File</a></li>
</ul></li>
<li class="chapter" data-level="15.8" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#limit-by-journal"><i class="fa fa-check"></i><b>15.8</b> Limit by journal</a></li>
<li class="chapter" data-level="15.9" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#obtaining-the-full-number-of-results"><i class="fa fa-check"></i><b>15.9</b> Obtaining the full number of results</a></li>
<li class="chapter" data-level="15.10" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#obtaining-the-number-of-records-across-plos-journals"><i class="fa fa-check"></i><b>15.10</b> Obtaining the number of records across PLOS Journals</a></li>
<li class="chapter" data-level="15.11" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#writing-the-results-and-using-a-codebook"><i class="fa fa-check"></i><b>15.11</b> Writing the results and using a codebook</a></li>
<li class="chapter" data-level="15.12" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#proximity-searching"><i class="fa fa-check"></i><b>15.12</b> Proximity Searching</a></li>
<li class="chapter" data-level="15.13" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#searching-using-multiple-phrases"><i class="fa fa-check"></i><b>15.13</b> Searching Using Multiple Phrases</a></li>
<li class="chapter" data-level="15.14" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#tidying-and-organising-the-data"><i class="fa fa-check"></i><b>15.14</b> Tidying and Organising the Data</a>
<ul>
<li class="chapter" data-level="15.14.1" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#renaming-a-column"><i class="fa fa-check"></i><b>15.14.1</b> Renaming a column</a></li>
</ul></li>
<li class="chapter" data-level="15.15" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#filling-blank-spaces"><i class="fa fa-check"></i><b>15.15</b> Filling Blank Spaces</a></li>
<li class="chapter" data-level="15.16" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#converting-dates"><i class="fa fa-check"></i><b>15.16</b> Converting Dates</a></li>
<li class="chapter" data-level="15.17" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#add-a-count"><i class="fa fa-check"></i><b>15.17</b> Add a count</a></li>
<li class="chapter" data-level="15.18" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#remove-a-column"><i class="fa fa-check"></i><b>15.18</b> Remove a column</a></li>
<li class="chapter" data-level="15.19" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#arranging-the-data"><i class="fa fa-check"></i><b>15.19</b> Arranging the Data</a></li>
<li class="chapter" data-level="15.20" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#dealing-with-duplicates"><i class="fa fa-check"></i><b>15.20</b> Dealing with Duplicates</a>
<ul>
<li class="chapter" data-level="15.20.1" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#spreading-data-using-spread-from-tidyr"><i class="fa fa-check"></i><b>15.20.1</b> Spreading data using <code>spread()</code> from <code>tidyr</code></a></li>
<li class="chapter" data-level="15.20.2" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#deleting-duplicates"><i class="fa fa-check"></i><b>15.20.2</b> Deleting Duplicates</a></li>
</ul></li>
<li class="chapter" data-level="15.21" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#restricting-searches-by-section"><i class="fa fa-check"></i><b>15.21</b> Restricting searches by section</a></li>
<li class="chapter" data-level="15.22" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#by-author"><i class="fa fa-check"></i><b>15.22</b> By author</a></li>
<li class="chapter" data-level="15.23" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#title-search-using-plostitle"><i class="fa fa-check"></i><b>15.23</b> Title search using <code>plostitle()</code></a></li>
<li class="chapter" data-level="15.24" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#abstract-search-using-plosabstract"><i class="fa fa-check"></i><b>15.24</b> Abstract search using <code>plosabstract()</code></a></li>
<li class="chapter" data-level="15.25" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#subject-area-using-plossubject"><i class="fa fa-check"></i><b>15.25</b> Subject Area using <code>plossubject()</code></a></li>
<li class="chapter" data-level="15.26" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#highlighting-terms-and-text-fragments-with-highplos"><i class="fa fa-check"></i><b>15.26</b> Highlighting terms and text fragments with highplos()</a>
<ul>
<li class="chapter" data-level="15.26.1" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#snippets-using-hl.snippets"><i class="fa fa-check"></i><b>15.26.1</b> Snippets using hl.snippets</a></li>
<li class="chapter" data-level="15.26.2" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#fragment-size-using-hl.fragsize"><i class="fa fa-check"></i><b>15.26.2</b> fragment size using hl.fragsize</a></li>
</ul></li>
<li class="chapter" data-level="15.27" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#get-the-full-text-of-one-or-more-articles"><i class="fa fa-check"></i><b>15.27</b> Get the full text of one or more articles</a></li>
<li class="chapter" data-level="15.28" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#writing-a-corpus-to-disk"><i class="fa fa-check"></i><b>15.28</b> Writing a corpus to disk</a></li>
<li class="chapter" data-level="15.29" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#round-up-9"><i class="fa fa-check"></i><b>15.29</b> Round Up</a></li>
<li class="chapter" data-level="15.30" data-path="scientific-literature-with-rplos.html"><a href="scientific-literature-with-rplos.html#resources-1"><i class="fa fa-check"></i><b>15.30</b> Resources</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/wipo-analytics/wipo-analytics.github.io" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The WIPO Manual on Open Source Patent Analytics (2nd edition)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="patent-infographics-with-r" class="section level1" number="14">
<h1><span class="header-section-number">Chapter 14</span> Patent Infographics with R</h1>
<p>In this chapter we will use RStudio to prepare patent data for visualisation in an infographic using online software tools.</p>
<p>Infographics are a popular way of presenting data in a way that is easy for a reader to understand without reading a long report. Infographics are well suited to presenting summaries of data with simple messages about key findings. A good infographic can encourage the audience to read a detailed report and is a tool for engagement with audiences during presentations of the findings of patent research.</p>
<p>Some patent offices have already been creating infographics as part of their reports to policy makers and other clients. The Instituto Nacional de Propiedade Industrial (INPI) in Brazil produces regular two page <a href="http://www.inpi.gov.br/menu-servicos/informacao/radares-tecnologicos">Technology Radar</a> (Radar Tecnologico) consisting of charts and maps that briefly summarise more detailed research on subjects such as <a href="http://www.inpi.gov.br/menu-servicos/arquivos-cedin/n08_radar_tecnologico_nano_residuos_versao_resumida_ingles_atualizada_20160122.pdf">Nanotechnology in Waste Management</a>. <a href="http://www.wipo.int/patentscope/en/programs/patent_landscapes/">WIPO Patent Landscape Reports</a>, which go into depth on patent activity for a particular area, are accompanied by one page infographics that have proved very popular such as the infographic accompanying a recent report on <a href="http://www.wipo.int/export/sites/www/patentscope/en/programs/patent_landscapes/reports/documents/assistivedevices_infographic.pdf">assistive devices</a>.</p>
<p>A growing number of companies are offering online infographic software services such as <a href="https://infogr.am/app/#/library">infogr.am</a>,<a href="http://www.easel.ly">easel.ly</a> <a href="https://magic.piktochart.com/templates">piktochart.com</a>, <a href="https://www.canva.com/create/infographics/">canva.com</a> or <a href="https://venngage.com">venngage.com</a> to mention only a selection of the offerings out there. The <a href="http://www.coolinfographics.com/tools/">Cool Infographics website</a> provides a useful overview of available tools.</p>
<p>One feature of many of these services is that they are based on a freemium model. Creating graphics is free but the ability to export files and the available formats for export of your masterpiece (e.g. high resolution or .pdf) often depend on upgrading to a monthly account at varying prices. In this chapter we test drive <a href="https://infogr.am/app/#/library">infogr.am</a> as a chart friendly service, albeit with export options that depend on a paid account.</p>
<p>This chapter is divided into two sections.</p>
<ol style="list-style-type: decimal">
<li>In part 1 we focus on using RStudio to prepare patent data for visualisation in infographics software using the <code>dplyr</code>, <code>tidyr</code> and <code>stringr</code> packages. This involves dealing with common problems with patent data such as concatenated fields, white space and creating counts of data fields.</li>
<li>In part 2 we produce an infographic from the data using <a href="https://infogr.am/app/#/library">infogr.am</a>.</li>
</ol>
<div id="getting-started-2" class="section level2" number="14.1">
<h2><span class="header-section-number">14.1</span> Getting Started</h2>
<p>To start with we need to ensure that RStudio and R for your operating system are installed by following the instructions on the RStudio website <a href="https://www.rstudio.com/products/rstudio/download/">here</a>. Do not forget to follow the link to also <a href="https://cran.rstudio.com">install R for your operating system</a>.</p>
<p>When working in RStudio it is good practice to work with projects. This will keep all of the files for a project in the same folder. To create a project go to File, New Project and create a project. Call the project something like infographic. Any file you create and save for the project will now be listed under the Files tab in RStudio.</p>
<p>R works using packages (libraries) and there are around 7,490 of them for a whole range of purposes. We will use just a few of them. To install a package we use the following. Copy and paste the code into the Console and press enter.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="patent-infographics-with-r.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>) <span class="co"># the group of packages you will need</span></span></code></pre></div>
<p>Packages can also be installed by selecting the Packages tab and typing the name of the package.</p>
<p>To load the packages (libraries) use the following or check the tick box in the Packages pane.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="patent-infographics-with-r.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr) </span>
<span id="cb28-2"><a href="patent-infographics-with-r.html#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) </span>
<span id="cb28-3"><a href="patent-infographics-with-r.html#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr) </span>
<span id="cb28-4"><a href="patent-infographics-with-r.html#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb28-5"><a href="patent-infographics-with-r.html#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<p>We are now ready to go.</p>
</div>
<div id="load-a-.csv-file-using-readr" class="section level2" number="14.2">
<h2><span class="header-section-number">14.2</span> Load a .csv file using <code>readr</code></h2>
<p>We will work with the <code>pizza_medium_clean</code> dataset in the online <a href="https://github.com/wipo-analytics/opensource-patent-analytics/tree/master/2_datasets">Github Manual repository</a>. If manually downloading a file remember to click on the file name and select <code>Raw</code> to download the actual file.</p>
<p>We can use the easy to use <code>read_csv()</code> function from the <code>readr</code> package to quickly read in our pizza data directly from the Github repository. Note the <code>raw</code> at the beginning of the filename.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="patent-infographics-with-r.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb29-2"><a href="patent-infographics-with-r.html#cb29-2" aria-hidden="true" tabindex="-1"></a>pizza <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://github.com/wipo-analytics/opensource-patent-analytics/blob/master/2_datasets/pizza_medium_clean/pizza.csv?raw=true&quot;</span>)</span></code></pre></div>
<p><code>readr</code> will display a warning for the file arising from its efforts to parse publication dates on import. We will ignore this as we will not be using this field.</p>
<p>As an alternative to importing directly from Github download the file and in RStudio use <code>File &gt; Import Dataset &gt; From .csv</code>. If you experience problems with direct import of a file the File &gt; Import Dataset approach will give you a range of easy to use controls for figuring this out (e.g. where .csv is actually a tab separated file).</p>
</div>
<div id="viewing-data" class="section level2" number="14.3">
<h2><span class="header-section-number">14.3</span> Viewing Data</h2>
<p>We can view data in a variety of ways.</p>
<ol style="list-style-type: decimal">
<li>In the console:</li>
</ol>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="patent-infographics-with-r.html#cb30-1" aria-hidden="true" tabindex="-1"></a>pizza</span></code></pre></div>
<pre><code>## # A tibble: 9,996 × 31
##    applicants_cleaned    applicants_clean… applicants_orga… applicants_original 
##    &lt;chr&gt;                 &lt;chr&gt;             &lt;chr&gt;            &lt;chr&gt;               
##  1 &lt;NA&gt;                  People            &lt;NA&gt;             &lt;NA&gt;                
##  2 Ventimeglia Jamie Jo… People            &lt;NA&gt;             Ventimeglia Jamie J…
##  3 Cordova Robert; Mart… People            &lt;NA&gt;             Cordova Robert;Mart…
##  4 Lazarillo De Tormes … Corporate         Lazarillo De To… LAZARILLO DE TORMES…
##  5 &lt;NA&gt;                  People            &lt;NA&gt;             &lt;NA&gt;                
##  6 Depoortere, Thomas    People            &lt;NA&gt;             DEPOORTERE, Thomas  
##  7 Frisco Findus Ag      Corporate         Frisco Findus Ag FRISCO-FINDUS AG    
##  8 Bicycle Tools Incorp… Corporate         Bicycle Tools I… Bicycle Tools Incor…
##  9 Castiglioni, Carlo    People            &lt;NA&gt;             CASTIGLIONI, CARLO  
## 10 &lt;NA&gt;                  People            &lt;NA&gt;             &lt;NA&gt;                
## # … with 9,986 more rows, and 27 more variables: inventors_cleaned &lt;chr&gt;,
## #   inventors_original &lt;chr&gt;, ipc_class &lt;chr&gt;, ipc_codes &lt;chr&gt;,
## #   ipc_names &lt;chr&gt;, ipc_original &lt;chr&gt;, ipc_subclass_codes &lt;chr&gt;,
## #   ipc_subclass_detail &lt;chr&gt;, ipc_subclass_names &lt;chr&gt;,
## #   priority_country_code &lt;chr&gt;, priority_country_code_names &lt;chr&gt;,
## #   priority_data_original &lt;chr&gt;, priority_date &lt;chr&gt;,
## #   publication_country_code &lt;chr&gt;, publication_country_name &lt;chr&gt;, …</code></pre>
<ol start="2" style="list-style-type: decimal">
<li><p>In Environment click on the blue arrow to see in the environment. Keep clicking to open a new window with the data.</p></li>
<li><p>Use the <code>View()</code> command (for data.frames and tables)</p></li>
</ol>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="patent-infographics-with-r.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(pizza)</span></code></pre></div>
<p>If possible use the View() command or environment. The difficulty with the console is that large amounts of data will simply stream past.</p>
</div>
<div id="identifying-types-of-object" class="section level2" number="14.4">
<h2><span class="header-section-number">14.4</span> Identifying Types of Object</h2>
<p>We often want to know what type of object we are working with and more details about the object so we know what to do later. Here are some of the most common commands for obtaining information about objects.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="patent-infographics-with-r.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(pizza) <span class="do">## type of object</span></span>
<span id="cb33-2"><a href="patent-infographics-with-r.html#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(pizza) <span class="do">## names of variables</span></span>
<span id="cb33-3"><a href="patent-infographics-with-r.html#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(pizza) <span class="do">## structure of object</span></span>
<span id="cb33-4"><a href="patent-infographics-with-r.html#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(pizza) <span class="do">## dimensions of the object</span></span></code></pre></div>
<p>The most useful command in this list is <code>str()</code> because this allows us to access the structure of the object and see its type.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="patent-infographics-with-r.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(pizza, <span class="at">max.level =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><code>str()</code> is particularly useful because we can see the names of the fields (vectors) and their type. Most patent data is a character vector with dates forming integers.</p>
</div>
<div id="working-with-data" class="section level2" number="14.5">
<h2><span class="header-section-number">14.5</span> Working with Data</h2>
<p>We will often want to select aspects of our data to focus on a specific set of columns or to create a graph. We might also want to add information, notably numeric counts.</p>
<p>The <code>dplyr</code> package provides a set of very handy functions for selecting, adding and counting data. The <code>tidyr</code> and <code>stringr</code> packages are sister packages that contain a range of other useful functions for working with our data. We have covered some of these in other chapters on graphing using R but will go through them quickly and then pull them together into a function that we can use across our dataset.</p>
<div id="select" class="section level3" number="14.5.1">
<h3><span class="header-section-number">14.5.1</span> Select</h3>
<p>In this case we will start by using the <code>select()</code> function to limit the data to specific columns. We can do this using their names or their numeric position (best for large number of columns e.g. 1:31). In <code>dplyr</code>, unlike most R packages, existing character columns do not require <code>""</code>.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="patent-infographics-with-r.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb35-2"><a href="patent-infographics-with-r.html#cb35-2" aria-hidden="true" tabindex="-1"></a>pizza_number <span class="ot">&lt;-</span> <span class="fu">select</span>(pizza, publication_number, publication_year)</span></code></pre></div>
<p>We now have a new data.frame that contains two columns. One with the year and one with the publication number. Note that we have created a new object called pizza_number using <code>&lt;-</code> and that after <code>select()</code> we have named our original data and the columns we want. A fundamental feature of select is that it will drop columns that we do not name. So it is best to create a new object using <code>&lt;-</code> if you want to keep your original data for later work.</p>
</div>
<div id="adding-data-with-mutate" class="section level3" number="14.5.2">
<h3><span class="header-section-number">14.5.2</span> Adding data with <code>mutate()</code></h3>
<p><code>mutate()</code> is a <code>dplyr</code> function that allows us to add data based on existing data in our data frame, for example to perform a calculation. In the case of patent data we normally lack a numeric field to use for counts. We can however assign a value to our publication field by using sum() and the number 1 as follows.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="patent-infographics-with-r.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb36-2"><a href="patent-infographics-with-r.html#cb36-2" aria-hidden="true" tabindex="-1"></a>pizza_number <span class="ot">&lt;-</span> <span class="fu">mutate</span>(pizza_number, <span class="at">n =</span> <span class="fu">sum</span>(<span class="at">publication_number =</span> <span class="dv">1</span>))</span></code></pre></div>
<p>When we view <code>pizza_number</code> we now have a value of 1 in the column <code>n</code> for each publication number. Note that in patent data a priority, application, publication or family number may occur multiple times and we would want to reduce the dataset to distinct records. For that we would use <code>n_distinct(pizza_number$publication_number)</code> from <code>dplyr</code> or <code>unique(pizza_number$publication_number)</code> from base R. Because the publication numbers are unique we can proceed.</p>
</div>
<div id="counting-data-using-count" class="section level3" number="14.5.3">
<h3><span class="header-section-number">14.5.3</span> Counting data using <code>count()</code></h3>
<p>At the moment, we have multiple instances of the same year (where a patent publication occurs in that year). We now want to calculate how many of our documents were published in each year. To do that we will use the <code>dplyr</code> function <code>count()</code>. We will use the publication_year and add <code>wt =</code> (for weight) with <code>n</code> as the value to count.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="patent-infographics-with-r.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb37-2"><a href="patent-infographics-with-r.html#cb37-2" aria-hidden="true" tabindex="-1"></a>pizza_total <span class="ot">&lt;-</span> <span class="fu">count</span>(pizza_number, publication_year, <span class="at">wt =</span> n) </span>
<span id="cb37-3"><a href="patent-infographics-with-r.html#cb37-3" aria-hidden="true" tabindex="-1"></a>pizza_total</span></code></pre></div>
<pre><code>## # A tibble: 58 × 2
##    publication_year     n
##               &lt;dbl&gt; &lt;dbl&gt;
##  1             1940     1
##  2             1954     1
##  3             1956     1
##  4             1957     1
##  5             1959     1
##  6             1962     1
##  7             1964     2
##  8             1966     1
##  9             1967     1
## 10             1968     8
## # … with 48 more rows</code></pre>
<p>When we now examine pizza_total, we will see the publication year and a summed value for the records in that year.</p>
<p>This raises the question of how we know that R has calculated the count correctly. We already know that there are 9996 records in the pizza dataset. To check our count is correct we can simply use sum and select the column we want to sum using <code>$</code>.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="patent-infographics-with-r.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(pizza_total<span class="sc">$</span>n)</span></code></pre></div>
<pre><code>## [1] 9996</code></pre>
<p>So, all is good and we can move on. The <code>$</code> sign is one of the main ways of subsetting to tell R that we want to work with a specific column (the others are “[” and “[[”).</p>
</div>
<div id="rename-a-field-with-rename" class="section level3" number="14.5.4">
<h3><span class="header-section-number">14.5.4</span> Rename a field with <code>rename()</code></h3>
<p>Next we will use <code>rename()</code> from <code>dplyr</code> to rename the fields. Note that understanding which field require quote marks can take some effort. In this case renaming the character vector publication_year as “pubyear” requires quotes while renaming the numeric vector “n” does not.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="patent-infographics-with-r.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb41-2"><a href="patent-infographics-with-r.html#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="patent-infographics-with-r.html#cb41-3" aria-hidden="true" tabindex="-1"></a>pizza_total <span class="ot">&lt;-</span> <span class="fu">rename</span>(pizza_total, <span class="at">pubyear =</span> publication_year, <span class="at">publications =</span> n)</span>
<span id="cb41-4"><a href="patent-infographics-with-r.html#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="patent-infographics-with-r.html#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pizza_total)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   pubyear publications
##     &lt;dbl&gt;        &lt;dbl&gt;
## 1    1940            1
## 2    1954            1
## 3    1956            1
## 4    1957            1
## 5    1959            1
## 6    1962            1</code></pre>
</div>
<div id="make-a-quickplot-with-qplot" class="section level3" number="14.5.5">
<h3><span class="header-section-number">14.5.5</span> Make a quickplot with <code>qplot()</code></h3>
<p>Using the <code>qplot()</code> function in <code>ggplot2</code> we can now draw a quick line graph. Note that qplot() is unusual in R because the data (pizza_total) appears after the coordinates. We will specify that we want a line using <code>geom =</code> (if geom is left out it will be a scatter plot). This will give us an idea of what our plot might look like in our infographic and actions we might want to take on the data.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="patent-infographics-with-r.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb43-2"><a href="patent-infographics-with-r.html#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(<span class="at">x =</span> pubyear, <span class="at">y =</span> publications, <span class="at">data =</span> pizza_total, <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>)</span></code></pre></div>
<p><img src="manual_bookdown_files/figure-html/qplot-1.png" width="1152" style="display: block; margin: auto;" /></p>
<!---![](images_foot/infogram/fig1_infographic.png)--->
<p>The plot reveals a data cliff in recent years. This normally reflects a lack of data for the last 2-3 years as recent documents feed through the system en route to publication.</p>
<p>It is a good idea to remove the data cliff by cutting the data 2-3 years prior to the present. In some cases two years is sufficient, but 3 years is a good rule of thumb.</p>
<p>We also have long tail of data with limited data from 1940 until the late 1970s. Depending on our purposes with the analysis we might want to keep this data (for historical analysis) or to focus in on a more recent period.</p>
<p>We will limit our data to specific values using the <code>dplyr</code> function <code>filter()</code>.</p>
</div>
<div id="filter-data-using-filter" class="section level3" number="14.5.6">
<h3><span class="header-section-number">14.5.6</span> Filter data using <code>filter()</code></h3>
<p>In contrast with <code>select()</code> which works with columns, <code>filter()</code> in <code>dplyr</code> works with rows. In this case we need to filter on the values in the pubyear column. To remove the data prior to 1990 we will use the greater than or equal to operator <code>&gt;=</code> on the pubyear column and we will use the less than or equal to <code>&lt;=</code> operator on the values after 2012.</p>
<p>One strength of <code>filter()</code> in <code>dplyr</code> is that it is easy to filter on multiple values in the same expression (unlike the very similar filter function in base R). The use of <code>filter()</code> will also remove the 30 records where the year is recorded as NA (Not Available). We will write this file to disk using the simple <code>write_csv()</code> from <code>readr</code>. To use <code>write_csv()</code> we first name our data (<code>pizza_total</code>) and then provide a file name with a .csv extension. In this case and other examples below we have used a descriptive file name bearing in mind that Windows systems have limitations on the length and type of characters that can be used in file names.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="patent-infographics-with-r.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb44-2"><a href="patent-infographics-with-r.html#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb44-3"><a href="patent-infographics-with-r.html#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="patent-infographics-with-r.html#cb44-4" aria-hidden="true" tabindex="-1"></a>pizza_total <span class="ot">&lt;-</span> <span class="fu">filter</span>(pizza_total, pubyear <span class="sc">&gt;=</span> <span class="dv">1990</span>, pubyear <span class="sc">&lt;=</span> <span class="dv">2012</span>)</span>
<span id="cb44-5"><a href="patent-infographics-with-r.html#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="patent-infographics-with-r.html#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pizza_total)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   pubyear publications
##     &lt;dbl&gt;        &lt;dbl&gt;
## 1    1990          139
## 2    1991          154
## 3    1992          212
## 4    1993          201
## 5    1994          162
## 6    1995          173</code></pre>
<p>When we print pizza_total to the console we will see that the data now covers the period 1990-2012. When using <code>filter()</code> on values in this way it is important to remember to apply this filter to any subsequent operations on the data (such as applicants) so that it matches the same data period.</p>
<p>To see our .csv file we can head over to the Files tab and, assuming that we have created a project, the file will now appear in the list of project files. Clicking on the file name will display the raw unformatted data in RStudio.</p>
</div>
</div>
<div id="simplify-code-with-pipes" class="section level2" number="14.6">
<h2><span class="header-section-number">14.6</span> Simplify code with pipes <code>%&gt;%</code></h2>
<p>So far we have handled the code one line at a time. But, one of the great strengths of using a programming language is that we can run multiple lines of code together. There are two basic ways that we can do this.</p>
<p>We will create a new temporary object <code>df</code> to demonstrate this.</p>
<ol style="list-style-type: decimal">
<li>The standard way</li>
</ol>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="patent-infographics-with-r.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb46-2"><a href="patent-infographics-with-r.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb46-3"><a href="patent-infographics-with-r.html#cb46-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">select</span>(pizza, publication_number, publication_year)</span>
<span id="cb46-4"><a href="patent-infographics-with-r.html#cb46-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">mutate</span>(df, <span class="at">n =</span> <span class="fu">sum</span>(<span class="at">publication_number =</span> <span class="dv">1</span>))</span>
<span id="cb46-5"><a href="patent-infographics-with-r.html#cb46-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">count</span>(df, publication_year, <span class="at">wt =</span> n)</span>
<span id="cb46-6"><a href="patent-infographics-with-r.html#cb46-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">rename</span>(df, <span class="st">&quot;pubyear&quot;</span> <span class="ot">=</span> publication_year, <span class="at">publications =</span> n)</span>
<span id="cb46-7"><a href="patent-infographics-with-r.html#cb46-7" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">filter</span>(df, pubyear <span class="sc">&gt;=</span> <span class="dv">1990</span>, pubyear <span class="sc">&lt;=</span> <span class="dv">2012</span>) </span>
<span id="cb46-8"><a href="patent-infographics-with-r.html#cb46-8" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(<span class="at">x =</span> pubyear, <span class="at">y =</span> publications, <span class="at">data =</span> df, <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>)</span></code></pre></div>
<p>The code we have just created is six lines long. If we select all of this code and run it in one go it will produce our graph.</p>
<p>One feature of this code is that each time we run a function on the object total we name it at the start of each function (e.g. mutate(df…)) and then we overwrite the object.</p>
<p>We can save quite a lot of typing and reduce the complexity of the code using the pipe operator introduced by the the <code>magrittr</code> package and then adopted in Hadley Wickham’s data wrangling and tidying packages.</p>
<ol start="2" style="list-style-type: decimal">
<li>Using pipes <code>%&gt;%</code></li>
</ol>
<p>Pipes are now a very popular way of writing R code because they simplify writing R code and speed it up. The most popular pipe is <code>%&gt;%</code> which means “this” then “that”. In this case we are going to create a new temporary object <code>df1</code> by first applying select to pizza, then mutate, count, rename and filter. Note that we only name our dataset once (in <code>select()</code>) and we do not need to keep overwriting the object.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="patent-infographics-with-r.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb47-2"><a href="patent-infographics-with-r.html#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb47-3"><a href="patent-infographics-with-r.html#cb47-3" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> </span>
<span id="cb47-4"><a href="patent-infographics-with-r.html#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(pizza, publication_number, publication_year) <span class="sc">%&gt;%</span></span>
<span id="cb47-5"><a href="patent-infographics-with-r.html#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">sum</span>(<span class="at">publication_number =</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb47-6"><a href="patent-infographics-with-r.html#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(publication_year, <span class="at">wt =</span> n) <span class="sc">%&gt;%</span></span>
<span id="cb47-7"><a href="patent-infographics-with-r.html#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">&quot;pubyear&quot;</span> <span class="ot">=</span> publication_year, <span class="at">publications =</span> n) <span class="sc">%&gt;%</span></span>
<span id="cb47-8"><a href="patent-infographics-with-r.html#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pubyear <span class="sc">&gt;=</span> <span class="dv">1990</span>, pubyear <span class="sc">&lt;=</span> <span class="dv">2012</span>) <span class="sc">%&gt;%</span></span>
<span id="cb47-9"><a href="patent-infographics-with-r.html#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">qplot</span>(<span class="at">x =</span> pubyear, <span class="at">y =</span> publications, <span class="at">data =</span> ., <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>)</span>
<span id="cb47-10"><a href="patent-infographics-with-r.html#cb47-10" aria-hidden="true" tabindex="-1"></a>df1</span></code></pre></div>
<p><img src="manual_bookdown_files/figure-html/piped-1.png" width="1152" style="display: block; margin: auto;" /></p>
<!---![](images_foot/infogram/fig2_infographic_qplot.png)--->
<p>In the standard code we typed <code>df</code> nine times to arrive at the same result. Using pipes we typed df1 once. Of greater importance is that the use of pipes simplifies the structure of R code by introducing a basic “this” then “that” logic which makes it easier to understand.</p>
<p>One point to note about this code is that <code>qplot()</code> requires us to name our data (in this case <code>df1</code>). However, <code>df1</code> is actually the final output of the code and does not exist as an input object before the final line is run. So, if we attempt to use <code>data = df1</code> in <code>qplot()</code> we will receive an error message. The way around this is to use <code>.</code> in place of our data object. That way <code>qplot()</code> will know we want to graph the outputs of the earlier code. Finally, we need to add an explicit call to <code>print()</code> to display the graph (without this the code will work but we will not see the graph).</p>
<p>If we now inspect the structure of the df1 object (using <code>str(df1)</code>) in the console, it will be a list. The reason for this is that it is an object with mixed components, including a data.frame with our data plus additional data setting out the contents of the plot. As there is no direct link between R and our infographics software this will create problems for us later because the infographics software won’t know how to interpret the list object. So, it is generally a good idea to use a straight data.frame by excluding the call to <code>qplot</code> and adding it later when needed as follows.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="patent-infographics-with-r.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb48-2"><a href="patent-infographics-with-r.html#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb48-3"><a href="patent-infographics-with-r.html#cb48-3" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> </span>
<span id="cb48-4"><a href="patent-infographics-with-r.html#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(pizza, publication_number, publication_year) <span class="sc">%&gt;%</span></span>
<span id="cb48-5"><a href="patent-infographics-with-r.html#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">sum</span>(<span class="at">publication_number =</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb48-6"><a href="patent-infographics-with-r.html#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(publication_year, <span class="at">wt =</span> n) <span class="sc">%&gt;%</span></span>
<span id="cb48-7"><a href="patent-infographics-with-r.html#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">&quot;pubyear&quot;</span> <span class="ot">=</span> publication_year, <span class="at">publications =</span> n) <span class="sc">%&gt;%</span></span>
<span id="cb48-8"><a href="patent-infographics-with-r.html#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pubyear <span class="sc">&gt;=</span> <span class="dv">1990</span>, pubyear <span class="sc">&lt;=</span> <span class="dv">2012</span>)</span>
<span id="cb48-9"><a href="patent-infographics-with-r.html#cb48-9" aria-hidden="true" tabindex="-1"></a>df2</span></code></pre></div>
<pre><code>## # A tibble: 23 × 2
##    pubyear publications
##      &lt;dbl&gt;        &lt;dbl&gt;
##  1    1990          139
##  2    1991          154
##  3    1992          212
##  4    1993          201
##  5    1994          162
##  6    1995          173
##  7    1996          180
##  8    1997          186
##  9    1998          212
## 10    1999          290
## # … with 13 more rows</code></pre>
<p>Note that in this case the only change is that we need to explicitly include the reference to the df2 data frame as the data argument in the call to <code>qplot()</code>.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="patent-infographics-with-r.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb50-2"><a href="patent-infographics-with-r.html#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(<span class="at">x =</span> pubyear, <span class="at">y =</span> publications, <span class="at">data =</span> df2, <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>)</span></code></pre></div>
<p><img src="manual_bookdown_files/figure-html/df2_qplot-1.png" width="1152" style="display: block; margin: auto;" /></p>
</div>
<div id="harmonising-data" class="section level2" number="14.7">
<h2><span class="header-section-number">14.7</span> Harmonising data</h2>
<p>One challenge with creating multiple tables from a baseline dataset is keeping track of subdatasets. At the moment we have two basic objects we will be working with:</p>
<ol style="list-style-type: decimal">
<li><code>pizza</code> - our raw dataset</li>
<li><code>pizza_total</code> - created via <code>pizza_number</code> limited to 1990_2012.</li>
</ol>
<p>In the remainder of the chapter we will want to create some additional datasets from our pizza dataset. These are:</p>
<ol style="list-style-type: decimal">
<li>Country trends</li>
<li>Applicants</li>
<li>International Patent Classification (IPC) Class</li>
<li>Phrases</li>
<li>Google</li>
<li>Google IPC</li>
<li>Google phrases</li>
</ol>
<p>We need to make sure that any data that we generate from our raw dataset matches the period for the <code>pizza_total</code> dataset. If we do not do this there is a risk that we will generate subdatasets with counts for the raw pizza dataset.</p>
<p>To handle this we will use <code>filter()</code> to create a new baseline dataset with an unambiguous name.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="patent-infographics-with-r.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb51-2"><a href="patent-infographics-with-r.html#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="patent-infographics-with-r.html#cb51-3" aria-hidden="true" tabindex="-1"></a>pizza_1990_2012 <span class="ot">&lt;-</span> <span class="fu">rename</span>(pizza, <span class="st">&quot;pubyear&quot;</span> <span class="ot">=</span> publication_year) <span class="sc">%&gt;%</span></span>
<span id="cb51-4"><a href="patent-infographics-with-r.html#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pubyear <span class="sc">&gt;=</span> <span class="dv">1990</span>, pubyear <span class="sc">&lt;=</span> <span class="dv">2012</span>)</span>
<span id="cb51-5"><a href="patent-infographics-with-r.html#cb51-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-6"><a href="patent-infographics-with-r.html#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pizza_1990_2012)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 31
##   applicants_cleaned         applicants_clean… applicants_orga… applicants_orig…
##   &lt;chr&gt;                      &lt;chr&gt;             &lt;chr&gt;            &lt;chr&gt;           
## 1 &lt;NA&gt;                       People            &lt;NA&gt;             &lt;NA&gt;            
## 2 Lazarillo De Tormes S L    Corporate         Lazarillo De To… LAZARILLO DE TO…
## 3 &lt;NA&gt;                       People            &lt;NA&gt;             &lt;NA&gt;            
## 4 Depoortere, Thomas         People            &lt;NA&gt;             DEPOORTERE, Tho…
## 5 Frisco Findus Ag           Corporate         Frisco Findus Ag FRISCO-FINDUS AG
## 6 Bicycle Tools Incorporated Corporate         Bicycle Tools I… Bicycle Tools I…
## # … with 27 more variables: inventors_cleaned &lt;chr&gt;, inventors_original &lt;chr&gt;,
## #   ipc_class &lt;chr&gt;, ipc_codes &lt;chr&gt;, ipc_names &lt;chr&gt;, ipc_original &lt;chr&gt;,
## #   ipc_subclass_codes &lt;chr&gt;, ipc_subclass_detail &lt;chr&gt;,
## #   ipc_subclass_names &lt;chr&gt;, priority_country_code &lt;chr&gt;,
## #   priority_country_code_names &lt;chr&gt;, priority_data_original &lt;chr&gt;,
## #   priority_date &lt;chr&gt;, publication_country_code &lt;chr&gt;,
## #   publication_country_name &lt;chr&gt;, publication_date &lt;chr&gt;, …</code></pre>
<p>In this case we start with a call to <code>rename()</code> to make this consistent with our pizza_total table and then use a pipe to filter the data on the year. Note here that when filtering raw data on a set of values it is important to inspect it first to check that the field is clean (e.g. not concatenated). If for some reason your data is concatenated (which happens quite a lot with patent data) then lookup <code>?tidyr::separate_rows</code>.</p>
<p>We are now in a position to create our country trends table.</p>
</div>
<div id="country-trends-using-spread-and-pivot_wider" class="section level2" number="14.8">
<h2><span class="header-section-number">14.8</span> Country Trends using <code>spread()</code> and <code>pivot_wider()</code></h2>
<p>There are two basic data formats: long and wide. Our pizza dataset is in long format because each column is a variable (e.g. <code>publication_country</code>) and each row in <code>publication_country</code> contains a country name. This is the most common and useful data format.</p>
<p>However, in some cases, such as <code>infogr.am</code> our visualisation software will expect the data to be in wide format. In this case each country name would become a variable (column name) with the years forming the rows and the number of records per year the observations. The key to this is the <code>tidyr()</code> function <code>spread()</code> and the more recent replacement <code>pivot_wider()</code>.</p>
<p>As above we will start off by using <code>select()</code> to create a table with the fields that we want. We will then use <code>mutate()</code> to add a numeric field and then count up that data. To illustrate the process run this code (we will not create an object).</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="patent-infographics-with-r.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb53-2"><a href="patent-infographics-with-r.html#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(pizza_1990_2012, publication_country_name, publication_number, pubyear) <span class="sc">%&gt;%</span></span>
<span id="cb53-3"><a href="patent-infographics-with-r.html#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">sum</span>(<span class="at">publication_number =</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb53-4"><a href="patent-infographics-with-r.html#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(publication_country_name, pubyear, <span class="at">wt =</span> n) <span class="sc">%&gt;%</span> </span>
<span id="cb53-5"><a href="patent-infographics-with-r.html#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 223 × 3
##    publication_country_name pubyear     n
##    &lt;chr&gt;                      &lt;dbl&gt; &lt;dbl&gt;
##  1 Canada                      1990    19
##  2 Canada                      1991    49
##  3 Canada                      1992    66
##  4 Canada                      1993    59
##  5 Canada                      1994    50
##  6 Canada                      1995    39
##  7 Canada                      1996    36
##  8 Canada                      1997    45
##  9 Canada                      1998    46
## 10 Canada                      1999    47
## # … with 213 more rows</code></pre>
<p>When we run this code we will see the results in long format. We now want to take our <code>publication_country_name</code> column and spread it to form columns with <code>n</code> as the values.</p>
<p>In using spread note that it takes a data argument (<code>pizza_1990_2012</code>), a key (<code>publication_country_name</code>), and value column (<code>n</code>) (created from <code>count()</code>). We are using pipes so the data only needs to be named in the first line. For additional arguments see <code>?spread()</code>.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="patent-infographics-with-r.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb55-2"><a href="patent-infographics-with-r.html#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb55-3"><a href="patent-infographics-with-r.html#cb55-3" aria-hidden="true" tabindex="-1"></a>country_totals <span class="ot">&lt;-</span> <span class="fu">select</span>(pizza_1990_2012, publication_country_name, publication_number, pubyear) <span class="sc">%&gt;%</span></span>
<span id="cb55-4"><a href="patent-infographics-with-r.html#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">sum</span>(<span class="at">publication_number =</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb55-5"><a href="patent-infographics-with-r.html#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(publication_country_name, pubyear, <span class="at">wt =</span> n) <span class="sc">%&gt;%</span></span>
<span id="cb55-6"><a href="patent-infographics-with-r.html#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(publication_country_name, n)</span>
<span id="cb55-7"><a href="patent-infographics-with-r.html#cb55-7" aria-hidden="true" tabindex="-1"></a>country_totals</span></code></pre></div>
<pre><code>## # A tibble: 23 × 17
##    pubyear Canada China `Eurasian Patent … `European Paten… Germany Israel Japan
##      &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;              &lt;dbl&gt;            &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1    1990     19    NA                 NA               22       2     NA    NA
##  2    1991     49    NA                 NA               29       2     NA    NA
##  3    1992     66    NA                 NA               36       2      1    NA
##  4    1993     59    NA                 NA               29       2     NA    NA
##  5    1994     50    NA                 NA               26       5     NA    NA
##  6    1995     39    NA                 NA               29       2      1    NA
##  7    1996     36     1                 NA               27       1      1    NA
##  8    1997     45    NA                 NA               34       1     NA    NA
##  9    1998     46    NA                 NA               36       1     NA    17
## 10    1999     47     2                  2               60       4     NA    26
## # … with 13 more rows, and 9 more variables: Korea, Republic of &lt;dbl&gt;,
## #   Mexico &lt;dbl&gt;, Patent Co-operation Treaty &lt;dbl&gt;, Portugal &lt;dbl&gt;,
## #   Russian Federation &lt;dbl&gt;, Singapore &lt;dbl&gt;, South Africa &lt;dbl&gt;, Spain &lt;dbl&gt;,
## #   United States of America &lt;dbl&gt;</code></pre>
<p>One problem with spread is that it can be difficult to remember the order of the arguments. In response to this the more recent and preferred approach is to use <code>pivot_wider()</code> which replaces spread (see also <code>pivot_longer()</code>. <code>pivot_wider()</code> takes two main arguments <code>names_from =</code> and <code>values_from</code>. This is a lot easier to remember with some practice. It is also more likely to be familiar if you have a background in Excel where pivot table.</p>
<p>We can achieve the same thing in a more transparent way with <code>pivot_wider()</code> as we see below.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="patent-infographics-with-r.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb57-2"><a href="patent-infographics-with-r.html#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb57-3"><a href="patent-infographics-with-r.html#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="patent-infographics-with-r.html#cb57-4" aria-hidden="true" tabindex="-1"></a>country_totals <span class="ot">&lt;-</span> <span class="fu">select</span>(pizza_1990_2012, publication_country_name, publication_number, pubyear) <span class="sc">%&gt;%</span></span>
<span id="cb57-5"><a href="patent-infographics-with-r.html#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">sum</span>(<span class="at">publication_number =</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb57-6"><a href="patent-infographics-with-r.html#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(publication_country_name, pubyear, <span class="at">wt =</span> n) <span class="sc">%&gt;%</span></span>
<span id="cb57-7"><a href="patent-infographics-with-r.html#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> publication_country_name, <span class="at">values_from =</span> n) </span>
<span id="cb57-8"><a href="patent-infographics-with-r.html#cb57-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-9"><a href="patent-infographics-with-r.html#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(country_totals)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 17
##   pubyear Canada China `Eurasian Patent … `European Patent… Germany Israel Japan
##     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;              &lt;dbl&gt;             &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1    1990     19    NA                 NA                22       2     NA    NA
## 2    1991     49    NA                 NA                29       2     NA    NA
## 3    1992     66    NA                 NA                36       2      1    NA
## 4    1993     59    NA                 NA                29       2     NA    NA
## 5    1994     50    NA                 NA                26       5     NA    NA
## 6    1995     39    NA                 NA                29       2      1    NA
## # … with 9 more variables: Korea, Republic of &lt;dbl&gt;, Mexico &lt;dbl&gt;,
## #   Patent Co-operation Treaty &lt;dbl&gt;, Portugal &lt;dbl&gt;, Russian Federation &lt;dbl&gt;,
## #   Singapore &lt;dbl&gt;, South Africa &lt;dbl&gt;, Spain &lt;dbl&gt;,
## #   United States of America &lt;dbl&gt;</code></pre>
<p>We now have data in wide format.</p>
<p>In some cases, such as infogr.am, visualisation software may expect the country names to be the name of rows and the column names to be years . We can modify our call to <code>pivot_wider()</code> by replacing the <code>publication_country_name</code> with <code>pubyear</code>. Then we will write the data to disk for use in our infographic.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="patent-infographics-with-r.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb59-2"><a href="patent-infographics-with-r.html#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb59-3"><a href="patent-infographics-with-r.html#cb59-3" aria-hidden="true" tabindex="-1"></a>country_totals <span class="ot">&lt;-</span> <span class="fu">select</span>(pizza_1990_2012, publication_country_name, publication_number, pubyear) <span class="sc">%&gt;%</span></span>
<span id="cb59-4"><a href="patent-infographics-with-r.html#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">sum</span>(<span class="at">publication_number =</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb59-5"><a href="patent-infographics-with-r.html#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(publication_country_name, pubyear, <span class="at">wt =</span> n) <span class="sc">%&gt;%</span> </span>
<span id="cb59-6"><a href="patent-infographics-with-r.html#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> pubyear, <span class="at">values_from =</span> n)</span>
<span id="cb59-7"><a href="patent-infographics-with-r.html#cb59-7" aria-hidden="true" tabindex="-1"></a>country_totals</span></code></pre></div>
<pre><code>## # A tibble: 16 × 24
##    publication_country_… `1990` `1991` `1992` `1993` `1994` `1995` `1996` `1997`
##    &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 Canada                    19     49     66     59     50     39     36     45
##  2 China                     NA     NA     NA     NA     NA     NA      1     NA
##  3 Eurasian Patent Orga…     NA     NA     NA     NA     NA     NA     NA     NA
##  4 European Patent Offi…     22     29     36     29     26     29     27     34
##  5 Germany                    2      2      2      2      5      2      1      1
##  6 Israel                    NA     NA      1     NA     NA      1      1     NA
##  7 Japan                     NA     NA     NA     NA     NA     NA     NA     NA
##  8 Korea, Republic of        NA     NA     NA      1     NA     NA      1      1
##  9 Mexico                    NA     NA     NA     NA     NA     NA     NA     NA
## 10 Patent Co-operation …      8     13     31     16     20     22     23     26
## 11 Portugal                  NA     NA     NA     NA     NA     NA     NA     NA
## 12 Russian Federation        NA     NA     NA     NA     NA     NA     NA      5
## 13 Singapore                 NA     NA     NA     NA     NA     NA     NA     NA
## 14 South Africa               2      3      3      3      3      1      9      7
## 15 Spain                     NA     NA     NA     NA     NA     NA     NA     NA
## 16 United States of Ame…     86     58     73     91     58     79     81     67
## # … with 15 more variables: 1998 &lt;dbl&gt;, 1999 &lt;dbl&gt;, 2000 &lt;dbl&gt;, 2001 &lt;dbl&gt;,
## #   2002 &lt;dbl&gt;, 2003 &lt;dbl&gt;, 2004 &lt;dbl&gt;, 2005 &lt;dbl&gt;, 2006 &lt;dbl&gt;, 2007 &lt;dbl&gt;,
## #   2008 &lt;dbl&gt;, 2009 &lt;dbl&gt;, 2010 &lt;dbl&gt;, 2011 &lt;dbl&gt;, 2012 &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="patent-infographics-with-r.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(country_totals, <span class="st">&quot;pizza_country_1990_2012.csv&quot;</span>)</span></code></pre></div>
<p>To restore the data to long format we would need to use <code>pivot_longer()</code> as the counterpart to <code>pivot_wider()</code> (formerly <code>gather()</code> was used as the counterpart to <code>spread()</code>). <code>gather()</code> takes a dataset, a key for the name of the column we want to gather the countries into, a value for the numeric count (in this case n), and finally the positions of the columns to gather in. Note here that we need to look up the column positions in <code>country_totals</code> (e.g. using <code>View()</code>) or count the columns using <code>ncol(country_totals)</code>.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="patent-infographics-with-r.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb62-2"><a href="patent-infographics-with-r.html#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="patent-infographics-with-r.html#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="co">#country_totals %&gt;% </span></span>
<span id="cb62-4"><a href="patent-infographics-with-r.html#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  pivot_longer(everything(), </span></span>
<span id="cb62-5"><a href="patent-infographics-with-r.html#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="co">#               names_to = c(&quot;pubyear&quot;, &quot;n&quot;),</span></span>
<span id="cb62-6"><a href="patent-infographics-with-r.html#cb62-6" aria-hidden="true" tabindex="-1"></a><span class="co">#               )</span></span>
<span id="cb62-7"><a href="patent-infographics-with-r.html#cb62-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-8"><a href="patent-infographics-with-r.html#cb62-8" aria-hidden="true" tabindex="-1"></a><span class="co">#gather(country_totals, year, n, 2:24) %&gt;%</span></span>
<span id="cb62-9"><a href="patent-infographics-with-r.html#cb62-9" aria-hidden="true" tabindex="-1"></a><span class="co">#  print()</span></span></code></pre></div>
<p>The combination of spread and gather work really well to prepare data in formats that are expected by other software. However, one of the main issues we encounter with patent data is that our data is not tidy because various fields are concatenated.</p>
</div>
<div id="tidying-data---separating-and-gathering" class="section level2" number="14.9">
<h2><span class="header-section-number">14.9</span> Tidying data - Separating and Gathering</h2>
<p>In patent data we often see concatenated fields with a separator (normally a <code>;</code>). These are typically applicant names, inventor names, International Patent Classification (IPC) codes, or document numbers (priority numbers, family numbers). We need to <code>tidy</code> this data prior to data cleaning (such as cleaning names) or to prepare for analysis and visualisation. For more on the concept of tidy data read <a href="http://vita.had.co.nz/papers/tidy-data.pdf">Hadley Wickham’s Tidy Data article</a>. The new <a href="http://r4ds.had.co.nz/tidy-data.html">R for Data Science book</a> by Garrett Grolemund and Hadley Wickham (see Chapter 12) is also strongly recommended.</p>
<p>To tidy patent data we will typically need to do two things.</p>
<ol style="list-style-type: decimal">
<li><p>Separate the data so that each cell contains a unique data point (e.g. a name, code or publication number). This normally involves separating data into columns.</p></li>
<li><p>Gathering the data back in. This involves transforming the data in the columns we have created into rows.</p></li>
</ol>
<p>Separating data into columns is very easy in tools such as Excel. However, gathering the data back into separate rows is remarkably difficult. Happily, this is very easy to do in R with the <code>tidyr</code> package.</p>
<p>The <code>tidyr</code> package contains three functions that are very useful when working with patent data. When dealing with concatenated fields in columns the key function is <code>separate_rows</code>.</p>
<p>Here we will work with the <code>applicants_cleaned</code> field in the pizza dataset. This field contains concatenated names with a <code>;</code> as the separator. For example, on lines 1_9 there are single applicant names or NA values. However, on lines 10 and line 59 we see:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="patent-infographics-with-r.html#cb63-1" aria-hidden="true" tabindex="-1"></a>Ehrno Flexible A<span class="sc">/</span>S; Stergaard, Ole</span>
<span id="cb63-2"><a href="patent-infographics-with-r.html#cb63-2" aria-hidden="true" tabindex="-1"></a>Farrell Brian; Mcnulty John; Vishoot Lisa</span></code></pre></div>
<p>The problem here is that when we are dealing with thousands of lines of applicant names we don’t know how many names might be concatenated into each cell as a basis for separating the data into columns. Once we had split the columns (for example using Text to Columns in Excel) we would then need to work out how to gather the columns into rows. The <code>separate_rows()</code> function from <code>tidyr</code> makes light work of this problem. To use the function we name the dataset, the column we want to separate into rows and the separator (sep).</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="patent-infographics-with-r.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb64-2"><a href="patent-infographics-with-r.html#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb64-3"><a href="patent-infographics-with-r.html#cb64-3" aria-hidden="true" tabindex="-1"></a>pizza1 <span class="ot">&lt;-</span> pizza_1990_2012 <span class="sc">%&gt;%</span> </span>
<span id="cb64-4"><a href="patent-infographics-with-r.html#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate_rows</span>(applicants_cleaned, <span class="at">sep =</span> <span class="st">&quot;;&quot;</span>)</span>
<span id="cb64-5"><a href="patent-infographics-with-r.html#cb64-5" aria-hidden="true" tabindex="-1"></a>pizza1</span></code></pre></div>
<pre><code>## # A tibble: 12,597 × 31
##    applicants_cleaned         applicants_clea… applicants_orga… applicants_orig…
##    &lt;chr&gt;                      &lt;chr&gt;            &lt;chr&gt;            &lt;chr&gt;           
##  1 &lt;NA&gt;                       People           &lt;NA&gt;              &lt;NA&gt;           
##  2 Lazarillo De Tormes S L    Corporate        Lazarillo De To… &quot;LAZARILLO DE T…
##  3 &lt;NA&gt;                       People           &lt;NA&gt;              &lt;NA&gt;           
##  4 Depoortere, Thomas         People           &lt;NA&gt;             &quot;DEPOORTERE, Th…
##  5 Frisco Findus Ag           Corporate        Frisco Findus Ag &quot;FRISCO-FINDUS …
##  6 Bicycle Tools Incorporated Corporate        Bicycle Tools I… &quot;Bicycle Tools …
##  7 Castiglioni, Carlo         People           &lt;NA&gt;             &quot;CASTIGLIONI, C…
##  8 &lt;NA&gt;                       People           &lt;NA&gt;              &lt;NA&gt;           
##  9 Bujalski, Wlodzimierz      People           &lt;NA&gt;             &quot;BUJALSKI, WLOD…
## 10 Ehrno Flexible A/S         Corporate; Peop… Ehrno Flexible … &quot;EHRNO FLEXIBLE…
## # … with 12,587 more rows, and 27 more variables: inventors_cleaned &lt;chr&gt;,
## #   inventors_original &lt;chr&gt;, ipc_class &lt;chr&gt;, ipc_codes &lt;chr&gt;,
## #   ipc_names &lt;chr&gt;, ipc_original &lt;chr&gt;, ipc_subclass_codes &lt;chr&gt;,
## #   ipc_subclass_detail &lt;chr&gt;, ipc_subclass_names &lt;chr&gt;,
## #   priority_country_code &lt;chr&gt;, priority_country_code_names &lt;chr&gt;,
## #   priority_data_original &lt;chr&gt;, priority_date &lt;chr&gt;,
## #   publication_country_code &lt;chr&gt;, publication_country_name &lt;chr&gt;, …</code></pre>
<p>Our original dataset contained 8,262 rows. Our new dataset split on applicant names contains 12,729 rows. The function has moved our target column from column 1 to column 31 in the data frame. We can easily move it back to inspect.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="patent-infographics-with-r.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb66-2"><a href="patent-infographics-with-r.html#cb66-2" aria-hidden="true" tabindex="-1"></a>pizza1 <span class="ot">&lt;-</span> pizza1 <span class="sc">%&gt;%</span> <span class="fu">select</span>(., <span class="dv">31</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">30</span>)</span></code></pre></div>
<p><code>separate_rows()</code> has done a great job but one of the problems with concatenated names is extra white space around the separator. We will deal with this next.</p>
<div id="trimming-with-stringr" class="section level3" number="14.9.1">
<h3><span class="header-section-number">14.9.1</span> Trimming with <code>stringr</code></h3>
<p>If we inspect the bottom of the column by subsetting into it using <code>$</code> we will see that a lot of the names have a leading whitespace space. This results from the separate exercise where the <code>;</code> is actually <code>;space</code>. Take a look at the last few rows of the data using <code>tail()</code>.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="patent-infographics-with-r.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(pizza1<span class="sc">$</span>applicants_cleaned, <span class="dv">20</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;Yahoo! Inc&quot;                        &quot;Clarcor Inc&quot;                      
##  [3] &quot;Holden Jeffrey A&quot;                  &quot; Vengroff Darren E&quot;               
##  [5] &quot;Casper Jeffrey L&quot;                  &quot; Erickson Braden J&quot;               
##  [7] &quot; Oppenheimer Alan A&quot;               &quot; Ray Madonna M&quot;                   
##  [9] &quot; Weber Jean L&quot;                     &quot;Pandey Neena&quot;                     
## [11] &quot; Sharma Sudhanshu&quot;                 &quot; Verizon Patent And Licensing Inc&quot;
## [13] &quot;Pandey Neena&quot;                      &quot; Sharma Sudhanshu&quot;                
## [15] &quot;Brown Michael&quot;                     &quot; Urban Scott&quot;                     
## [17] &quot;Brown Michael&quot;                     &quot; Urban Scott&quot;                     
## [19] &quot;Cole Lorin R&quot;                      &quot; Middleton Scott W&quot;</code></pre>
<p>This is a big issue because any counts that we make later on using the applicants_cleaned field will treat “Oppenheimer Alan A” and ” Oppenheimer Alan A” as separate names when they should be grouped together.</p>
<p>We can address this in a couple of ways. One approach is to recognise that actually our separator is not a simple <code>";"</code> but <code>";space"</code> in our call to <code>separate_rows()</code>. In that case the call to <code>separate_rows()</code> would actually be <code>sep = "; "</code>. We will add a line of code to illustrate the impact of this change.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="patent-infographics-with-r.html#cb69-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> pizza_1990_2012 <span class="sc">%&gt;%</span> </span>
<span id="cb69-2"><a href="patent-infographics-with-r.html#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate_rows</span>(., applicants_cleaned, <span class="at">sep =</span> <span class="st">&quot;; &quot;</span>)</span>
<span id="cb69-3"><a href="patent-infographics-with-r.html#cb69-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-4"><a href="patent-infographics-with-r.html#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect the problem entry</span></span>
<span id="cb69-5"><a href="patent-infographics-with-r.html#cb69-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(tmp<span class="sc">$</span>applicants_cleaned, <span class="dv">20</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;Yahoo! Inc&quot;                       &quot;Clarcor Inc&quot;                     
##  [3] &quot;Holden Jeffrey A&quot;                 &quot;Vengroff Darren E&quot;               
##  [5] &quot;Casper Jeffrey L&quot;                 &quot;Erickson Braden J&quot;               
##  [7] &quot;Oppenheimer Alan A&quot;               &quot;Ray Madonna M&quot;                   
##  [9] &quot;Weber Jean L&quot;                     &quot;Pandey Neena&quot;                    
## [11] &quot;Sharma Sudhanshu&quot;                 &quot;Verizon Patent And Licensing Inc&quot;
## [13] &quot;Pandey Neena&quot;                     &quot;Sharma Sudhanshu&quot;                
## [15] &quot;Brown Michael&quot;                    &quot;Urban Scott&quot;                     
## [17] &quot;Brown Michael&quot;                    &quot;Urban Scott&quot;                     
## [19] &quot;Cole Lorin R&quot;                     &quot;Middleton Scott W&quot;</code></pre>
<p>Another way to address this, is to use the <code>str_trim()</code> function from the <code>stringr</code> package.</p>
<p>We can address this problem using a function from the <code>stringr</code> package <code>str_trim()</code>. We have a choice with <code>str_trim()</code> on whether to trim the whitespace on the right, left or both. Here we will choose both.</p>
<p>Because we are seeking to modify an existing column (not to create a new vector or data.frame) we will use <code>$</code> to select the column and as the data for the <code>str_trim()</code> function. That will apply the function to the applicants column in pizza1.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="patent-infographics-with-r.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb71-2"><a href="patent-infographics-with-r.html#cb71-2" aria-hidden="true" tabindex="-1"></a>pizza1<span class="sc">$</span>applicants_cleaned <span class="ot">&lt;-</span> <span class="fu">str_trim</span>(pizza1<span class="sc">$</span>applicants_cleaned, <span class="at">side =</span> <span class="st">&quot;both&quot;</span>)</span>
<span id="cb71-3"><a href="patent-infographics-with-r.html#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(pizza1<span class="sc">$</span>applicants_cleaned, <span class="dv">20</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;Yahoo! Inc&quot;                       &quot;Clarcor Inc&quot;                     
##  [3] &quot;Holden Jeffrey A&quot;                 &quot;Vengroff Darren E&quot;               
##  [5] &quot;Casper Jeffrey L&quot;                 &quot;Erickson Braden J&quot;               
##  [7] &quot;Oppenheimer Alan A&quot;               &quot;Ray Madonna M&quot;                   
##  [9] &quot;Weber Jean L&quot;                     &quot;Pandey Neena&quot;                    
## [11] &quot;Sharma Sudhanshu&quot;                 &quot;Verizon Patent And Licensing Inc&quot;
## [13] &quot;Pandey Neena&quot;                     &quot;Sharma Sudhanshu&quot;                
## [15] &quot;Brown Michael&quot;                    &quot;Urban Scott&quot;                     
## [17] &quot;Brown Michael&quot;                    &quot;Urban Scott&quot;                     
## [19] &quot;Cole Lorin R&quot;                     &quot;Middleton Scott W&quot;</code></pre>
<p>Note that when using <code>str_trim()</code> we use subsetting to modify the applicants column in place. There is possibly a more efficient way of doing this with pipes but this appears difficult because the data.frame needs to exist for <code>str_trim()</code> to act on in place or we end up with a vector of applicant names rather than a data.frame. A solution to this problem is provided on Stack Overflow<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>.</p>
<p>In practice, the most efficient solution in this case is to recognise that the separator for <code>separate_rows</code> is <code>";space"</code>. However, that will not always be true making the tools in <code>stringr</code> invaluable. To learn more about string manipulation in R try <a href="http://r4ds.had.co.nz/strings.html">Chapter 14 of R for Data Science by Garrett Grolemund and Hadley Wickham</a>.</p>
<p>We can tie the steps so far together using pipes into the following simpler code that we will become the applicants table for use in the infographic. We will add a call to rename and rename applicants_cleaned to tidy up.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="patent-infographics-with-r.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb73-2"><a href="patent-infographics-with-r.html#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb73-3"><a href="patent-infographics-with-r.html#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb73-4"><a href="patent-infographics-with-r.html#cb73-4" aria-hidden="true" tabindex="-1"></a>applicants <span class="ot">&lt;-</span> pizza <span class="sc">%&gt;%</span> </span>
<span id="cb73-5"><a href="patent-infographics-with-r.html#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(., <span class="st">&quot;pubyear&quot;</span> <span class="ot">=</span> publication_year) <span class="sc">%&gt;%</span></span>
<span id="cb73-6"><a href="patent-infographics-with-r.html#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pubyear <span class="sc">&gt;=</span> <span class="dv">1990</span>, pubyear <span class="sc">&lt;=</span> <span class="dv">2012</span>) <span class="sc">%&gt;%</span></span>
<span id="cb73-7"><a href="patent-infographics-with-r.html#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate_rows</span>(applicants_cleaned, <span class="at">sep =</span> <span class="st">&quot;; &quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb73-8"><a href="patent-infographics-with-r.html#cb73-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">applicants =</span> applicants_cleaned) <span class="sc">%&gt;%</span> </span>
<span id="cb73-9"><a href="patent-infographics-with-r.html#cb73-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">31</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">30</span>) <span class="co"># moves separated column to the beginning (could use everything?)</span></span>
<span id="cb73-10"><a href="patent-infographics-with-r.html#cb73-10" aria-hidden="true" tabindex="-1"></a>applicants</span></code></pre></div>
<pre><code>## # A tibble: 12,597 × 31
##    title_original  applicants applicants_clea… applicants_orga… applicants_orig…
##    &lt;chr&gt;           &lt;chr&gt;      &lt;chr&gt;            &lt;chr&gt;            &lt;chr&gt;           
##  1 PIZZA           &lt;NA&gt;       People           &lt;NA&gt;              &lt;NA&gt;           
##  2 IMPROVED PIZZA  Lazarillo… Corporate        Lazarillo De To… &quot;LAZARILLO DE T…
##  3 Pizza separator &lt;NA&gt;       People           &lt;NA&gt;              &lt;NA&gt;           
##  4 Pizza separator Depoorter… People           &lt;NA&gt;             &quot;DEPOORTERE, Th…
##  5 PIZZA PREPARAT… Frisco Fi… Corporate        Frisco Findus Ag &quot;FRISCO-FINDUS …
##  6 Pizza Cutter    Bicycle T… Corporate        Bicycle Tools I… &quot;Bicycle Tools …
##  7 PIZZA BOX       Castiglio… People           &lt;NA&gt;             &quot;CASTIGLIONI, C…
##  8 PIZZA BOX       &lt;NA&gt;       People           &lt;NA&gt;              &lt;NA&gt;           
##  9 MORE ATTRACTIV… Bujalski,… People           &lt;NA&gt;             &quot;BUJALSKI, WLOD…
## 10 PIZZA PACKAGING Ehrno Fle… Corporate; Peop… Ehrno Flexible … &quot;EHRNO FLEXIBLE…
## # … with 12,587 more rows, and 26 more variables: inventors_cleaned &lt;chr&gt;,
## #   inventors_original &lt;chr&gt;, ipc_class &lt;chr&gt;, ipc_codes &lt;chr&gt;,
## #   ipc_names &lt;chr&gt;, ipc_original &lt;chr&gt;, ipc_subclass_codes &lt;chr&gt;,
## #   ipc_subclass_detail &lt;chr&gt;, ipc_subclass_names &lt;chr&gt;,
## #   priority_country_code &lt;chr&gt;, priority_country_code_names &lt;chr&gt;,
## #   priority_data_original &lt;chr&gt;, priority_date &lt;chr&gt;,
## #   publication_country_code &lt;chr&gt;, publication_country_name &lt;chr&gt;, …</code></pre>
<p>We will want to create a plot with the applicants data in our infographic software. For that we need to introduce a field to count on. We might also want to establish a cut off point based on the number of records per applicant.</p>
<p>In this code we will simply print the applicants ranked in descending order. The second to last line of the code provides a filter on the number of records. This value can be changed after inspecting the data. The final line omits NA values (otherwise the top result) where an applicant name is not available.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="patent-infographics-with-r.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb75-2"><a href="patent-infographics-with-r.html#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb75-3"><a href="patent-infographics-with-r.html#cb75-3" aria-hidden="true" tabindex="-1"></a>applicant_count <span class="ot">&lt;-</span> applicants <span class="sc">%&gt;%</span> </span>
<span id="cb75-4"><a href="patent-infographics-with-r.html#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(., applicants, publication_number) <span class="sc">%&gt;%</span></span>
<span id="cb75-5"><a href="patent-infographics-with-r.html#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">sum</span>(<span class="at">publication_number =</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb75-6"><a href="patent-infographics-with-r.html#cb75-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(applicants, <span class="at">wt =</span> n) <span class="sc">%&gt;%</span></span>
<span id="cb75-7"><a href="patent-infographics-with-r.html#cb75-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb75-8"><a href="patent-infographics-with-r.html#cb75-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;=</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb75-9"><a href="patent-infographics-with-r.html#cb75-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb75-10"><a href="patent-infographics-with-r.html#cb75-10" aria-hidden="true" tabindex="-1"></a>applicant_count </span></code></pre></div>
<pre><code>## # A tibble: 6,110 × 2
##    applicants                               n
##    &lt;chr&gt;                                &lt;dbl&gt;
##  1 Graphic Packaging International, Inc   154
##  2 Kraft Foods Holdings, Inc              132
##  3 Google Inc                             123
##  4 Microsoft Corporation                   88
##  5 The Pillsbury Company                   83
##  6 General Mills, Inc                      77
##  7 Nestec                                  76
##  8 The Procter &amp; Gamble Company            59
##  9 Pizza Hut, Inc                          57
## 10 Yahoo! Inc                              54
## # … with 6,100 more rows</code></pre>
<p>If we inspect applicant count using <code>View(applicant_count)</code> we have 6,178 rows. That is far too many to display in an infographic. So, next we will filter the data on the value for the top ten (54). Then we will write the data to a .csv file using the simple <code>write_csv()</code> from <code>readr</code>.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="patent-infographics-with-r.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb77-2"><a href="patent-infographics-with-r.html#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb77-3"><a href="patent-infographics-with-r.html#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb77-4"><a href="patent-infographics-with-r.html#cb77-4" aria-hidden="true" tabindex="-1"></a>applicant_count <span class="ot">&lt;-</span> applicants <span class="sc">%&gt;%</span> </span>
<span id="cb77-5"><a href="patent-infographics-with-r.html#cb77-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(., applicants, publication_number) <span class="sc">%&gt;%</span></span>
<span id="cb77-6"><a href="patent-infographics-with-r.html#cb77-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">sum</span>(<span class="at">publication_number =</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb77-7"><a href="patent-infographics-with-r.html#cb77-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(applicants, <span class="at">wt =</span> n) <span class="sc">%&gt;%</span></span>
<span id="cb77-8"><a href="patent-infographics-with-r.html#cb77-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb77-9"><a href="patent-infographics-with-r.html#cb77-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;=</span> <span class="dv">54</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb77-10"><a href="patent-infographics-with-r.html#cb77-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb77-11"><a href="patent-infographics-with-r.html#cb77-11" aria-hidden="true" tabindex="-1"></a>applicant_count </span></code></pre></div>
<pre><code>## # A tibble: 10 × 2
##    applicants                               n
##    &lt;chr&gt;                                &lt;dbl&gt;
##  1 Graphic Packaging International, Inc   154
##  2 Kraft Foods Holdings, Inc              132
##  3 Google Inc                             123
##  4 Microsoft Corporation                   88
##  5 The Pillsbury Company                   83
##  6 General Mills, Inc                      77
##  7 Nestec                                  76
##  8 The Procter &amp; Gamble Company            59
##  9 Pizza Hut, Inc                          57
## 10 Yahoo! Inc                              54</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="patent-infographics-with-r.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(applicant_count, <span class="st">&quot;pizza_applicants_1990_2012.csv&quot;</span>)</span></code></pre></div>
<p>When we inspect <code>applicant_count</code> we will see that Graphic Packaging International is the top result with 154 results with Google ranking third with 123 results followed by Microsoft. This could suggest that Google and Microsoft are suddenly entering the market for online pizza sales or pizza making software or, as is more likely, that there are uses other uses of the word pizza in patent data that we are not aware of.</p>
<p>As part of our infographic we will want to explore this intriguing result in more detail. We can do this by creating a subdataset for Google using <code>filter()</code>.</p>
</div>
</div>
<div id="selecting-applicants-using-filter" class="section level2" number="14.10">
<h2><span class="header-section-number">14.10</span> Selecting applicants using <code>filter()</code></h2>
<p>As we saw above, while <code>select()</code> functions with columns, <code>filter()</code> from <code>dplyr</code> works with rows. Here we will filter the data to select the rows in the applicants column that contain Google Inc. and then write that to a .csv for use in our infographic. Note the use of double <code>==</code> and the quotes around “Google Inc”.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="patent-infographics-with-r.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb80-2"><a href="patent-infographics-with-r.html#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb80-3"><a href="patent-infographics-with-r.html#cb80-3" aria-hidden="true" tabindex="-1"></a>google <span class="ot">&lt;-</span> applicants <span class="sc">%&gt;%</span> </span>
<span id="cb80-4"><a href="patent-infographics-with-r.html#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(., applicants <span class="sc">==</span> <span class="st">&quot;Google Inc&quot;</span>)</span>
<span id="cb80-5"><a href="patent-infographics-with-r.html#cb80-5" aria-hidden="true" tabindex="-1"></a>google</span></code></pre></div>
<pre><code>## # A tibble: 123 × 31
##    title_original  applicants applicants_clea… applicants_orga… applicants_orig…
##    &lt;chr&gt;           &lt;chr&gt;      &lt;chr&gt;            &lt;chr&gt;            &lt;chr&gt;           
##  1 Location based… Google Inc Corporate; Peop… Google Inc       Hafsteinsson Gu…
##  2 AUTHORITATIVE … Google Inc Corporate        Google Inc       GOOGLE INC.     
##  3 Location-Based… Google Inc Corporate; Peop… Google Inc       GOOGLE INC.;HAF…
##  4 Controlling th… Google Inc Corporate; Peop… Google Inc       GOOGLE, INC.;BE…
##  5 METHOD AND SYS… Google Inc Corporate        Google Inc       GOOGLE INC.     
##  6 Routing querie… Google Inc Corporate        Google Inc       GOOGLE INC.     
##  7 METHODS AND SY… Google Inc Corporate        Google Inc       GOOGLE INC.     
##  8 Aspect-based s… Google Inc Corporate; Peop… Google Inc       Reis George;Goo…
##  9 Interpreting l… Google Inc Corporate        Google Inc       GOOGLE INC.     
## 10 Interpreting l… Google Inc Corporate        Google Inc       GOOGLE INC.     
## # … with 113 more rows, and 26 more variables: inventors_cleaned &lt;chr&gt;,
## #   inventors_original &lt;chr&gt;, ipc_class &lt;chr&gt;, ipc_codes &lt;chr&gt;,
## #   ipc_names &lt;chr&gt;, ipc_original &lt;chr&gt;, ipc_subclass_codes &lt;chr&gt;,
## #   ipc_subclass_detail &lt;chr&gt;, ipc_subclass_names &lt;chr&gt;,
## #   priority_country_code &lt;chr&gt;, priority_country_code_names &lt;chr&gt;,
## #   priority_data_original &lt;chr&gt;, priority_date &lt;chr&gt;,
## #   publication_country_code &lt;chr&gt;, publication_country_name &lt;chr&gt;, …</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="patent-infographics-with-r.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(google, <span class="st">&quot;google_1990_2012.csv&quot;</span>)</span></code></pre></div>
<p>Note that the correct result for the period 1990 to 2012 for Google is 123 records from 191 records across the whole pizza dataset. The correct result will be achieved only where you use the filtered, separated and trimmed data we created in the applicants data frame.</p>
</div>
<div id="generating-ipc-tables" class="section level2" number="14.11">
<h2><span class="header-section-number">14.11</span> Generating IPC Tables</h2>
<p>In the next step we will want to generate two tables containing International Patent Classification (IPC) data. IPC codes and the Cooperative Patent Classification (CPC, not present in this dataset) provide information on the technologies involved in a patent document. The IPC is hierarchical and proceeds from the general class level to the detailed group and subgroup level. Experience reveals that the majority of patent documents receive more than one IPC code to more fully describe the technological aspects of patent documents.</p>
<p>The pizza dataset contains IPC codes on the class and the subclass level in concatenated fields. One important consideration in using IPC data is that the descriptions are long and can be difficult for non-specialists to grasp. This can make visualising the data difficult and often requires manual efforts to edit labels for display.</p>
<p>We now want to generate three IPC tables.</p>
<ol style="list-style-type: decimal">
<li>A general IPC table for the pizza dataset</li>
<li>A general IPC table for the Google dataset</li>
<li>A more detailed IPC subclass table for the Google dataset</li>
</ol>
<p>For ease of presentation in an infographic we will use the <code>ipc_class</code> field. For many patent analytics purposes this will be too general. However it has the advantage of being easy to visualise.</p>
<p>To generate the table we can use a generic function based on the code developed for dealing with the applicants data. We will call the function patent_count().</p>
<!--- rewrite this function--->
<!--- rewritten function--->
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="patent-infographics-with-r.html#cb83-1" aria-hidden="true" tabindex="-1"></a>patent_count <span class="ot">&lt;-</span> <span class="cf">function</span> (<span class="at">data =</span> <span class="cn">NULL</span>, <span class="at">col =</span> <span class="cn">NULL</span>, <span class="at">count_col =</span>  <span class="cn">NULL</span>, <span class="at">n_results =</span> n_results, <span class="at">sep =</span> <span class="st">&quot;[^[:alnum:]]+&quot;</span>) </span>
<span id="cb83-2"><a href="patent-infographics-with-r.html#cb83-2" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb83-3"><a href="patent-infographics-with-r.html#cb83-3" aria-hidden="true" tabindex="-1"></a>  p_count <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb83-4"><a href="patent-infographics-with-r.html#cb83-4" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(., .data[[col]], .data[[count_col]]) <span class="sc">%&gt;%</span></span>
<span id="cb83-5"><a href="patent-infographics-with-r.html#cb83-5" aria-hidden="true" tabindex="-1"></a>    tidyr<span class="sc">::</span><span class="fu">separate_rows</span>(.data[[col]], <span class="at">sep =</span> <span class="st">&quot;[;]&quot;</span>) <span class="sc">%&gt;%</span> <span class="co"># was sep</span></span>
<span id="cb83-6"><a href="patent-infographics-with-r.html#cb83-6" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="sc">!!</span><span class="at">col :=</span> stringr<span class="sc">::</span><span class="fu">str_trim</span>(.data[[col]], <span class="at">side =</span> <span class="st">&quot;both&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb83-7"><a href="patent-infographics-with-r.html#cb83-7" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">n =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb83-8"><a href="patent-infographics-with-r.html#cb83-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(.data[[col]]) <span class="sc">%&gt;%</span> </span>
<span id="cb83-9"><a href="patent-infographics-with-r.html#cb83-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(., <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb83-10"><a href="patent-infographics-with-r.html#cb83-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>()</span>
<span id="cb83-11"><a href="patent-infographics-with-r.html#cb83-11" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>The <code>patent_count()</code> function is based on the the code we developed for applicants. It contains variations to make it work as a function. The function takes four arguments:</p>
<ol style="list-style-type: decimal">
<li>col = the concatenated column that we want to split and gather back in</li>
<li>col_count = a column for generating counts (in this dataset the publication_number)</li>
<li>n_results = the number of results we want to see in the new table (typically 10 or 20 for visualisation). This is equivalent to the number of rows that you want to see.</li>
<li>sep = the separator to use to separate the data in col. With patent data this is almost always “;” (as <code>;space</code>.</li>
</ol>
<p>To generate the <code>ipc_class</code> data we can do the following and then write the file to .csv. Note that we have set the number of results <code>n_results</code> to 10.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="patent-infographics-with-r.html#cb84-1" aria-hidden="true" tabindex="-1"></a>pizza_ipc_class <span class="ot">&lt;-</span> <span class="fu">patent_count</span>(<span class="at">data =</span> pizza_1990_2012, <span class="at">col =</span> <span class="st">&quot;ipc_class&quot;</span>, <span class="at">count_col =</span> <span class="st">&quot;publication_number&quot;</span>, <span class="at">n_results =</span> <span class="dv">10</span>, <span class="at">sep =</span> <span class="st">&quot;;&quot;</span>)</span>
<span id="cb84-2"><a href="patent-infographics-with-r.html#cb84-2" aria-hidden="true" tabindex="-1"></a>pizza_ipc_class</span></code></pre></div>
<pre><code>## # A tibble: 111 × 2
##    ipc_class                                               n
##    &lt;chr&gt;                                               &lt;int&gt;
##  1 A21: Baking                                          2233
##  2 A23: Foods Or Foodstuffs                             1843
##  3 B65: Conveying                                       1383
##  4 G06: Computing                                       1326
##  5 A47: Furniture                                        932
##  6 H04: Electric Communication Technique                 747
##  7 H05: Electric Techniques Not Otherwise Provided For   613
##  8 F24: Heating                                          512
##  9 A61: Medical Or Veterinary Science                    318
## 10 G07: Checking                                         226
## # … with 101 more rows</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="patent-infographics-with-r.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co">#write_csv(pizza_ipc_class, &quot;pizza_ipcclass_1990_2012.csv&quot;)</span></span></code></pre></div>
<p>Note that this dataset is based on the main <code>pizza_1990_2012</code> dataset (including cases where no applicant name is available). The reason we have not used the applicants dataset is because that dataset will duplicate the IPC field for each split of an applicant name. As a result it will over count the IPCs by the number of applicants on a document name. As this suggests, it is important to be careful when working with data that has been tidied because of the impact on other counts.</p>
<p>This problem does not apply in the case of our Google data because the only applicant listed in that data is Google (excluding co-applicants). We can therefore safely use the Google dataset to identify the IPC codes.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="patent-infographics-with-r.html#cb87-1" aria-hidden="true" tabindex="-1"></a>google_ipc_class <span class="ot">&lt;-</span> <span class="fu">patent_count</span>(<span class="at">data =</span> google, <span class="at">col =</span> <span class="st">&quot;ipc_class&quot;</span>, <span class="at">count_col =</span> <span class="st">&quot;publication_number&quot;</span>, <span class="at">n_results =</span> <span class="dv">10</span>, <span class="at">sep =</span> <span class="st">&quot;;&quot;</span>)</span>
<span id="cb87-2"><a href="patent-infographics-with-r.html#cb87-2" aria-hidden="true" tabindex="-1"></a>google_ipc_class</span></code></pre></div>
<pre><code>## # A tibble: 7 × 2
##   ipc_class                                 n
##   &lt;chr&gt;                                 &lt;int&gt;
## 1 G06: Computing                          105
## 2 H04: Electric Communication Technique    17
## 3 G01: Measuring                           14
## 4 G09: Educating                           11
## 5 G10: Musical Instruments                  7
## 6 A63: Sports                               1
## 7 G08: Signalling                           1</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="patent-infographics-with-r.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(google_ipc_class, <span class="st">&quot;google_ipcclass_1990_2012.csv&quot;</span>)</span></code></pre></div>
<p>There are only 7 classes and as we might expect they are dominated by computing. We might want to dig into this in a little more detail and so let’s also create an IPC subclass field.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="patent-infographics-with-r.html#cb90-1" aria-hidden="true" tabindex="-1"></a>google_ipc_subclass <span class="ot">&lt;-</span> <span class="fu">patent_count</span>(<span class="at">data =</span> google, <span class="at">col =</span> <span class="st">&quot;ipc_subclass_detail&quot;</span>, <span class="at">count_col =</span> <span class="st">&quot;publication_number&quot;</span>, <span class="at">n_results =</span> <span class="dv">10</span>, <span class="at">sep =</span> <span class="st">&quot;;&quot;</span>)</span>
<span id="cb90-2"><a href="patent-infographics-with-r.html#cb90-2" aria-hidden="true" tabindex="-1"></a>google_ipc_subclass</span></code></pre></div>
<pre><code>## # A tibble: 16 × 2
##    ipc_subclass_detail                                                         n
##    &lt;chr&gt;                                                                   &lt;int&gt;
##  1 G06F: Electric Digital Data Processing                                     89
##  2 G06Q: Data Processing Systems Or Methods, Specially Adapted For Admini…    24
##  3 G01C: Measuring Distances, Levels Or Bearings                              14
##  4 G09B: Educational Or Demonstration Appliances                               9
##  5 G10L: Speech Analysis Or Synthesis                                          7
##  6 H04W: Wireless Communication Networks                                       7
##  7 G09G: Arrangements Or Circuits For Control Of Indicating Devices Using…     5
##  8 H04B: Transmission                                                          4
##  9 H04L: Transmission Of Digital Information, E.G. Telegraphic Communicat…     4
## 10 H04M: Telephonic Communication                                              4
## 11 G06K: Recognition Of Data                                                   3
## 12 H04N: Pictorial Communication, E.G. Television                              3
## 13 A63F: Card, Board, Or Roulette Games                                        1
## 14 G06N: Computer Systems Based On Specific Computational Models               1
## 15 G06T: Image Data Processing Or Generation, In General                       1
## 16 G08G: Traffic Control Systems                                               1</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="patent-infographics-with-r.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(google_ipc_subclass, <span class="st">&quot;google_ipcsubclass_1990_2012.csv&quot;</span>)</span></code></pre></div>
<p>We now have the data on technology areas that we need to understand our data. The next and final step is to generate data from the text fields.</p>
<div id="phrases-tables" class="section level3" number="14.11.1">
<h3><span class="header-section-number">14.11.1</span> Phrases Tables</h3>
<p>We will be using data from words and phrases in the titles of patent documents for use in a word cloud in our infographic. It is possible to generate this type of data in R directly using the <code>tm</code> and <code>NLP</code> packages. Our pizza dataset already contains a title field broken down into phrases using Vantagepoint software and so we will use that. We will use the field <code>title_nlp_multiword_phrases</code> as phrases are generally more informative than individual words. Once again we will use our general <code>patent_count()</code> function although experimentation may be needed to identify the number of phrases that visualise well in a word cloud.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="patent-infographics-with-r.html#cb93-1" aria-hidden="true" tabindex="-1"></a>pizza_phrases <span class="ot">&lt;-</span> <span class="fu">patent_count</span>(<span class="at">data =</span> pizza_1990_2012, <span class="at">col =</span> <span class="st">&quot;title_nlp_multiword_phrases&quot;</span>, <span class="at">count_col =</span> <span class="st">&quot;publication_number&quot;</span>, <span class="at">n_results =</span> <span class="dv">15</span>, <span class="at">sep =</span> <span class="st">&quot;;&quot;</span>)</span>
<span id="cb93-2"><a href="patent-infographics-with-r.html#cb93-2" aria-hidden="true" tabindex="-1"></a>pizza_phrases</span></code></pre></div>
<pre><code>## # A tibble: 6,323 × 2
##    title_nlp_multiword_phrases     n
##    &lt;chr&gt;                       &lt;int&gt;
##  1 &lt;NA&gt;                          475
##  2 Food Product                  179
##  3 Microwave Ovens               137
##  4 Making Same                    48
##  5 conveyor Oven                  46
##  6 Crust Pizza                    44
##  7 microwave Heating              41
##  8 Bakery Product                 40
##  9 pizza Box                      40
## 10 Microwave Cooking              39
## # … with 6,313 more rows</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="patent-infographics-with-r.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(pizza_phrases, <span class="st">&quot;pizza_phrases_1990_2012.csv&quot;</span>)</span></code></pre></div>
<p>Now we do the same with the Google data.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="patent-infographics-with-r.html#cb96-1" aria-hidden="true" tabindex="-1"></a>google_phrases <span class="ot">&lt;-</span> <span class="fu">patent_count</span>(<span class="at">data =</span> google, <span class="at">col =</span> <span class="st">&quot;title_nlp_multiword_phrases&quot;</span>, <span class="at">count_col =</span> <span class="st">&quot;publication_number&quot;</span>, <span class="at">n_results =</span> <span class="dv">15</span>, <span class="at">sep =</span> <span class="st">&quot;;&quot;</span>)</span>
<span id="cb96-2"><a href="patent-infographics-with-r.html#cb96-2" aria-hidden="true" tabindex="-1"></a>google_phrases</span></code></pre></div>
<pre><code>## # A tibble: 68 × 2
##    title_nlp_multiword_phrases              n
##    &lt;chr&gt;                                &lt;int&gt;
##  1 Digital Map System                      10
##  2 conversion Path Performance Measures     9
##  3 Mobile Device                            8
##  4 Search Results                           8
##  5 Geographical Relevance                   4
##  6 Local Search Results                     4
##  7 Location Prominence                      4
##  8 Network Speech Recognizers               4
##  9 Processing Queries                       4
## 10 Search Query                             4
## # … with 58 more rows</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="patent-infographics-with-r.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(google_phrases, <span class="st">&quot;google_phrases_1990_2012.csv&quot;</span>)</span></code></pre></div>
<p>We now have the following .csv files.</p>
<ol style="list-style-type: decimal">
<li><code>pizza_total_1990_2012</code></li>
<li><code>pizza_country_1990_2012</code></li>
<li><code>pizza_applicants_1990_2012</code></li>
<li><code>pizza_ipcclass_1990_2012</code></li>
<li><code>pizza_phrases_1990_2012</code></li>
<li><code>Google_1990_2012</code></li>
<li><code>Google_ipclass_1990_2012</code></li>
<li><code>Google_ipcsubclass_1990_2012</code></li>
<li><code>Google_phrases-1990_2012</code></li>
</ol>
</div>
</div>
<div id="creating-an-infographic-in-infogr.am" class="section level2" number="14.12">
<h2><span class="header-section-number">14.12</span> Creating an infographic in infogr.am</h2>
<p>If you are starting this chapter here then download the datasets we will be using as a single zip file from the Manual repository <a href="https://github.com/wipo-analytics/opensource-patent-analytics/blob/master/2_datasets/infographic/infographic.zip?raw=true">here</a> and then unzip the file.</p>
<p>We first need to sign up for a free account with <a href="https://infogr.am/">infogr.am</a></p>
<p><img src="images/infogram/fig1_infogram_front.png" /></p>
<p>We will then see a page with some sample infographics to provide ideas to get you started.</p>
<p><img src="images/infogram/fig2_infogram_login.png" /></p>
<p>Click on one of the infograms with a graph such as Trends in Something and then click inside the graph box itself and select the edit button in the top right.</p>
<p><img src="images/infogram/fig3_infogram_findedit.png" /></p>
<p>This will open up a data panel with the toy data displayed.</p>
<p><img src="images/infogram/fig4_infogram_datapanel.png" /></p>
<p>We want to replace this data by choosing the upload button and selecting our <code>pizza_country_1990_2012.csv</code> file.</p>
<p><img src="images/infogram/fig5_infogram_panelgraph.png" /></p>
<p>We now have a decent looking graph for our country trends data where we can see the number of records per country and year by hovering over the relevant data points. While some of the countries with low frequency data are crunched at the bottom (and would be better displayed in a separate graph), hovering over the data or over a country name will display the relevant country activity. We will therefore live with this.</p>
<p>We now want to start adding story elements by clicking on the edit button in the title. Next we can start adding new boxes using the menu icons on the right. Here we have changed the title, added a simple body text for the data credit and then a quote from someone describing themselves as the Head of Pizza Analytics.</p>
<p><img src="images/infogram/fig6_infogram_paneltext.png" /></p>
<p>Next we need to start digging into the data using our IPC, applicants and phrases data.</p>
<p>To work with our IPC class data we will add a bar chart and load the data. To do this select the graph icon in the right and then Bar. Once again we will choose edit and then load our <code>pizza_ipcclass_1990_2012</code> dataset. Then we can add a descriptive text box. We can then continue to add elements as follows:</p>
<ol style="list-style-type: decimal">
<li>applicants bar chart</li>
<li>pizza phrases by selecting graph and word cloud</li>
<li>Google ipc-subclass</li>
<li>Google word cloud.</li>
</ol>
<p>One useful approach to developing an infographic is to start by adding the images and then add titles and text boxes to raise key points. In infogram new text boxes appear below existing boxes but can be repositioned by dragging and dropping boxes onto each other.</p>
<p>One nice feature of infogram is that it is easy to share the infographic with others through a url, an embed code or on facebook or via twitter.</p>
<p>At the end of the infographic it is a good idea to provide a link where the reader can obtain more information, such as the full report or the underlying data. In this case we will add a link to the Tableau workbook on pizza patent activity that we developed in an earlier <a href="https://public.tableau.com/profile/wipo.open.source.patent.analytics.manual#!/vizhome/pizzapatents/Overview">chapter</a>.</p>
<p>Our final infographic should look something like <a href="https://infogr.am/trends_in_something">this</a>.</p>
<div id="round-up-8" class="section level3" number="14.12.1">
<h3><span class="header-section-number">14.12.1</span> Round Up</h3>
<p>In this chapter we have concentrated on using R to tidy patent data in order to create an online infographic using free software. Using our trusty pizza patent data from WIPO Patentscope we walked through the process of wrangling and tidying patent data first using short lines of code that we then combined into a reusable function. As this introduction to tidying data in R has hopefully revealed, R and packages such as <code>dplyr</code>, <code>tidyr</code> and <code>stringr</code> provide very useful tools for working with patent data, and they are free and well supported.</p>
<p>In the final part of the chapter we used the data we had generated in RStudio to create an infographic using infogr.am that we then shared online. Infogram is just one of a number of online infographic services and it is well worth trying other services such as <a href="https://www.easel.ly">easel.ly</a> to find a service that meets your needs.</p>
<p>As regular users of R will already know, it is already possible to produce all of these graphics (such as word clouds) directly in R using tools such as <code>ggplot2</code>, <code>plotly</code> and word clouds using packages such as <code>wordcloud</code>. Some of these topics have been covered in other chapters and for more on text mining and word clouds in R see this recent article on <a href="http://www.r-bloggers.com/building-wordclouds-in-r/">R-bloggers</a>. None of the infographic services we viewed appeared to offer an API that would enable a direct connection with R. There also seems to be a gap in R’s packages where infographics might sit with this <a href="http://www.r-bloggers.com/r-how-to-layout-and-design-an-infographic/">2015 R-bloggers article</a> providing a walk through on how to create a basic infographic.</p>

</div>
</div>
</div>



<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p><a href="http://stackoverflow.com/questions/25975827/how-to-feed-the-result-of-a-pipe-chain-magrittr-to-an-object" class="uri">http://stackoverflow.com/questions/25975827/how-to-feed-the-result-of-a-pipe-chain-magrittr-to-an-object</a><a href="patent-infographics-with-r.html#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="patent-analytics-with-plotly.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="scientific-literature-with-rplos.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
